<?php

use Illuminate\Database\Seeder;

class CityTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::insert("INSERT INTO city (name, state_province) VALUES 
					('Aguascalientes', 1),
					('Asientos', 1),
					('Calvillo', 1),
					('Cosío', 1),
					('Jesús María', 1),
					('NO_DATA', 1),
					('Pabellón de Arteaga', 1),
					('Rincón de Romos', 1),
					('San Francisco de los Romo', 1),
					('Tepezalá', 1),
					('Ensenada', 2),
					('Mexicali', 2),
					('NO_DATA', 2),
					('Playas de Rosarito', 2),
					('Rodolfo Sánchez T. (Maneadero)', 2),
					('San Felipe', 2),
					('Tecate', 2),
					('Tijuana', 2),
					('Cabo San Lucas', 3),
					('Ciudad Constitución', 3),
					('Guerrero Negro', 3),
					('Heroica Mulegé', 3),
					('La Paz', 3),
					('Loreto', 3),
					('NO_DATA', 3),
					('Puerto Adolfo López Mateos', 3),
					('San Ignacio', 3),
					('San José del Cabo', 3),
					('Santa Rosalía', 3),
					('Todos Santos', 3),
					('Villa Alberto Andrés Alvarado Arámburo', 3),
					('Calkini', 4),
					('Candelaria', 4),
					('Champotón', 4),
					('Ciudad del Carmen', 4),
					('Escárcega', 4),
					('Hecelchakán', 4),
					('Hopelchén', 4),
					('NO_DATA', 4),
					('Pomuch', 4),
					('Sabancuy', 4),
					('San Francisco de Campeche', 4),
					('Allende', 5),
					('Arteaga', 5),
					('Castaños', 5),
					('Ciudad Acuña', 5),
					('Ciudad Melchor Múzquiz', 5),
					('Cuatro Ciénegas de Carranza', 5),
					('Francisco I. Madero (Chávez)', 5),
					('Frontera', 5),
					('Matamoros', 5),
					('Monclova', 5),
					('Morelos', 5),
					('Nadadores', 5),
					('Nava', 5),
					('NO_DATA', 5),
					('Nueva Rosita', 5),
					('Parras de la Fuente', 5),
					('Piedras Negras', 5),
					('Ramos Arizpe', 5),
					('Sabinas', 5),
					('Saltillo', 5),
					('San Buenaventura', 5),
					('San Pedro', 5),
					('Torreón', 5),
					('Viesca', 5),
					('Zaragoza', 5),
					('Ciudad de Armería', 6),
					('Ciudad de Villa de Álvarez', 6),
					('Colima', 6),
					('Manzanillo', 6),
					('NO_DATA', 6),
					('Tecoman', 6),
					('Acala', 7),
					('Arriaga', 7),
					('Cacahoatán', 7),
					('Chiapa de Corzo', 7),
					('Cintalapa de Figueroa', 7),
					('Comitán de Domínguez', 7),
					('Huixtla', 7),
					('Jiquipilas', 7),
					('Las Margaritas', 7),
					('Las Rosas', 7),
					('Mapastepec', 7),
					('Motozintla de Mendoza', 7),
					('NO_DATA', 7),
					('Ocosingo', 7),
					('Ocozocoautla de Espinosa', 7),
					('Palenque', 7),
					('Pichucalco', 7),
					('Pijijiapan', 7),
					('Puerto Madero (San Benito)', 7),
					('Reforma', 7),
					('San Cristóbal de las Casas', 7),
					('Tapachula de Córdova y Ordóñez', 7),
					('Tonalá', 7),
					('Tuxtla Gutiérrez', 7),
					('Venustiano Carranza', 7),
					('Villaflores', 7),
					('Bachíniva', 8),
					('Chihuahua', 8),
					('Colonia Anáhuac', 8),
					('Cuauhtémoc', 8),
					('Delicias', 8),
					('Hidalgo del Parral', 8),
					('José Mariano Jiménez', 8),
					('Juan Aldama', 8),
					('Juárez', 8),
					('Madera', 8),
					('Manuel Ojinaga', 8),
					('NO_DATA', 8),
					('Nuevo Casas Grandes', 8),
					('Santa Rosalía de Camargo', 8),
					('Saucillo', 8),
					('Ciudad de México', 9),
					('Canatlán', 10),
					('Ciudad Lerdo', 10),
					('El Salto', 10),
					('Francisco I. Madero', 10),
					('Gómez Palacio', 10),
					('Nombre de Dios', 10),
					('NO_DATA', 10),
					('Peñón Blanco', 10),
					('San Juan del Río del Centauro del Norte', 10),
					('Santa María del Oro', 10),
					('Santiago Papasquiaro', 10),
					('Vicente Guerrero', 10),
					('Victoria de Durango', 10),
					('Abasolo', 11),
					('Acámbaro', 11),
					('Apaseo el Alto', 11),
					('Apaseo el Grande', 11),
					('Celaya', 11),
					('Ciudad Manuel Doblado', 11),
					('Comonfort', 11),
					('Cortazar', 11),
					('Cuerámaro', 11),
					('Doctor Mora', 11),
					('Dolores Hidalgo Cuna de la Independencia Nacional', 11),
					('Empalme Escobedo (Escobedo)', 11),
					('Guanajuato', 11),
					('Huanámaro', 11),
					('Irapuato', 11),
					('Jaral del Progreso', 11),
					('Jerácuaro', 11),
					('León de los Aldama', 11),
					('Marfil', 11),
					('Moroleón', 11),
					('NO_DATA', 11),
					('Pénjamo', 11),
					('Purísima de Bustos', 11),
					('Rincón de Tamayo', 11),
					('Romita', 11),
					('Salamanca', 11),
					('Salvatierra', 11),
					('San Diego de la Unión', 11),
					('San Francisco del Rincón', 11),
					('San José Iturbide', 11),
					('San Luis de la Paz', 11),
					('San miguel de Allende', 11),
					('Santa Cruz Juventino Rosas', 11),
					('Santiago Maravatío', 11),
					('Silao', 11),
					('Tarandacuao', 11),
					('Uriangato', 11),
					('Valle de Santiago', 11),
					('Villagrán', 11),
					('Yuriria', 11),
					('Acapulco de Juárez', 12),
					('Arcelia', 12),
					('Atoyac de Álvarez', 12),
					('Ayutla de los Libres', 12),
					('Azoyú', 12),
					('Buenavista de Cuellar', 12),
					('Chilapa de Álvarez', 12),
					('Chilpancingo de los Bravo', 12),
					('Ciudad Altamirano', 12),
					('Ciudad Apaxtla de Castrejón', 12),
					('Copala', 12),
					('Coyuca de Benítez', 12),
					('Coyuca de Catalán', 12),
					('Cruz Grande', 12),
					('Cuajinicuilapa', 12),
					('Cutzamala de Pinzón', 12),
					('Huamuxtitlan', 12),
					('Huitzuco', 12),
					('Iguala de la Independencia', 12),
					('La Unión', 12),
					('Marquelia', 12),
					('NO_DATA', 12),
					('Ocotito', 12),
					('Olinalá', 12),
					('Petatlán', 12),
					('San Jerénimo de Juárez', 12),
					('San Luis Acatlán', 12),
					('San Luis de la Loma', 12),
					('San Luis San Pedro', 12),
					('San Marcos', 12),
					('Taxco de Alarcón', 12),
					('Técpan de Galeana', 12),
					('Teloloapan', 12),
					('Tepecoacuilco de Trujano', 12),
					('Tierra Colorada', 12),
					('Tixtla de Guerrero', 12),
					('Tlalixtaquilla', 12),
					('Tlapa de Comonfort', 12),
					('Tlapehuala', 12),
					('Zihuatanejo', 12),
					('Zumpango del Río', 12),
					('Actopan', 13),
					('Apan', 13),
					('Ciudad de Fray Bernardino de Sahagún', 13),
					('Cruz Azul', 13),
					('Huejutla de Reyes', 13),
					('Ixmiquilpan', 13),
					('NO_DATA', 13),
					('Pachuca de Soto', 13),
					('Santiago Tulantepec', 13),
					('Tepeapulco', 13),
					('Tepeji del Rio', 13),
					('Tizayuca', 13),
					('Tlaxcoapan', 13),
					('Tula de Allende', 13),
					('Tulancingo', 13),
					('Zimapan', 13),
					('Acatlán de Juárez', 14),
					('Ahualulco de Mercado', 14),
					('Ajijic', 14),
					('Ameca', 14),
					('Arandas', 14),
					('Atotonilco el Alto', 14),
					('Autlán de Navarro', 14),
					('Chapala', 14),
					('Cihuatlán', 14),
					('Ciudad Guzmán', 14),
					('Cocula', 14),
					('Colotlán', 14),
					('El Grullo', 14),
					('El Quince (San José el Quince)', 14),
					('Etzatlán', 14),
					('Guadalajara', 14),
					('Huejuquilla el Alto', 14),
					('Jalostotitlán', 14),
					('Jamay', 14),
					('Jocotepec', 14),
					('La Barca', 14),
					('La Resolana', 14),
					('Lagos de Moreno', 14),
					('Las Pintitas', 14),
					('Magdalena', 14),
					('NO_DATA', 14),
					('Ocotlán', 14),
					('Poncitlán', 14),
					('Puerto Vallarta', 14),
					('San Diego de Alejandría', 14),
					('San Ignacio Cerro Gordo', 14),
					('San José el Verde (El Verde)', 14),
					('San Juan de los Lagos', 14),
					('San Julián', 14),
					('San Miguel el Alto', 14),
					('Sayula', 14),
					('Tala', 14),
					('Talpa de Allende', 14),
					('Tamazula de Gordiano', 14),
					('Tecalitlán', 14),
					('Teocaltiche', 14),
					('Tepatitlán de Morelos', 14),
					('Tequila', 14),
					('Tlajomulco de Zúñiga', 14),
					('Tlaquepaque', 14),
					('Tonalá', 14),
					('Tototlán', 14),
					('Tuxpan', 14),
					('Unión de San Antonio', 14),
					('Valle de Guadalupe', 14),
					('Villa Corona', 14),
					('Villa Hidalgo', 14),
					('Yahualica de González Gallo', 14),
					('Zacoalco de Torres', 14),
					('Zapopan', 14),
					('Zapotiltic', 14),
					('Almoloya de Juárez', 15),
					('Amatepec', 15),
					('Capulhuac', 15),
					('Chalco de Díaz Covarrubias', 15),
					('Chiconcuac', 15),
					('Chimalhuacán', 15),
					('Ciudad Adolfo López Mateos', 15),
					('Ciudad Nezahualcoyotl', 15),
					('Coacalco de Berriozabal', 15),
					('Cuautitlán', 15),
					('Cuautitlán Izcalli', 15),
					('Ecatepec de Morelos', 15),
					('Huixquilucan de Degollado', 15),
					('Ixtapaluca', 15),
					('Juchitepec de Mariano Riva Palacio', 15),
					('Los Reyes Acaquilpan (La Paz)', 15),
					('Melchor Ocampo', 15),
					('Metepec', 15),
					('Naucalpan de Juárez', 15),
					('NO_DATA', 15),
					('Ocoyoacac', 15),
					('San Mateo Atenco', 15),
					('San Vicente Chicoloapan de Juárez', 15),
					('Santa Maria Tultepec', 15),
					('Tecamac de Felipe Villanueva', 15),
					('Tejupilco de Hidalgo', 15),
					('Tepotzotlán', 15),
					('Tequixquiac', 15),
					('Texcoco de Mora', 15),
					('Tlalnepantla de Baz', 15),
					('Toluca de Lerdo', 15),
					('Tultitlán de Mariano Escobedo', 15),
					('Valle de Chalco Solidaridad', 15),
					('Villa Nicolás Romero', 15),
					('Xonacatlán', 15),
					('Zumpango', 15),
					('Apatzingán de la Constitución', 16),
					('Ciudad Hidalgo', 16),
					('Ciudad Lázaro Cárdenas', 16),
					('Cotija de la Paz', 16),
					('Cuitzeo del Porvenir', 16),
					('Heroica Zitácuaro', 16),
					('Huetamo de Núñez', 16),
					('Jacona de Plancarte', 16),
					('Jiquilpan de Juárez', 16),
					('La piedad de Cabadas', 16),
					('Las Guacamayas', 16),
					('Los Reyes de Salgado', 16),
					('Maravatío de Ocampo', 16),
					('Morelia', 16),
					('NO_DATA', 16),
					('Nueva Italia de Ruiz', 16),
					('Paracho de Verduzco', 16),
					('Pátzcuaro', 16),
					('Puruándiro', 16),
					('Sahuayo de Morelos', 16),
					('Tacámbaro de Codallos', 16),
					('Tangancícuaro de Arista', 16),
					('Tuxpan', 16),
					('Uruapan', 16),
					('Yurécuaro', 16),
					('Zacapu', 16),
					('Zamora de Hidalgo', 16),
					('Zinapécuaro de Figueroa', 16),
					('Cuautla (Cuautla de Morelos)', 17),
					('Cuernavaca', 17),
					('Galeana', 17),
					('Jojutla', 17),
					('NO_DATA', 17),
					('Puente de Ixtla', 17),
					('Santa Rosa Treinta', 17),
					('Tlaquiltenango', 17),
					('Zacatepec de Hidalgo', 17),
					('Acaponeta', 18),
					('Ahuacatlán', 18),
					('Bucerías', 18),
					('Compostela', 18),
					('Francisco I. Madero (Puga)', 18),
					('Ixtlán del Río', 18),
					('Jala', 18),
					('La peñita de Jaltemba', 18),
					('Las Varas', 18),
					('NO_DATA', 18),
					('Ruiz', 18),
					('San Blas', 18),
					('San pedro Lagunillas', 18),
					('Santiago Ixcuintla', 18),
					('Tecuala', 18),
					('Tepic', 18),
					('Tuxpan', 18),
					('Villa Hidalgo (El Nuevo)', 18),
					('Xalisco', 18),
					('Anáhuac', 19),
					('Cadereyta Jiménez', 19),
					('Ciénega de Flores', 19),
					('Ciudad Apodaca', 19),
					('Ciudad Benito Juárez', 19),
					('Ciudad General Escobedo', 19),
					('Ciudad Sabinas Hidalgo', 19),
					('Ciudad Santa Catarina', 19),
					('Doctor Arroyo', 19),
					('El cercado', 19),
					('García', 19),
					('Guadalupe', 19),
					('Hualahuises', 19),
					('Linares', 19),
					('Montemorelos', 19),
					('Monterrey', 19),
					('NO_DATA', 19),
					('San Nicolás de los Garza', 19),
					('San Pedro Garza García', 19),
					('Santiago', 19),
					('Asuncion Nochixtlán', 20),
					('Bahias de Huatulco', 20),
					('Chahuites', 20),
					('Ciudad Ixtepec', 20),
					('Cosolapa', 20),
					('Cuilápam de Guerrero', 20),
					('El Camarón', 20),
					('El Rosario', 20),
					('Heroica Ciudad de Ejutla de Crespo', 20),
					('Heroica Ciudad de Huajuapan de León', 20),
					('Heroica Ciudad de Tlaxiaco', 20),
					('Juchitán (Juchitán de Zaragoza)', 20),
					('Lagunas', 20),
					('Loma Bonita', 20),
					('Mariscala de Juárez', 20),
					('Matías Romero Avendaño', 20),
					('Miahuatlán de Porfirio Díaz', 20),
					('Natividad', 20),
					('NO_DATA', 20),
					('Oaxaca de Juárez', 20),
					('Ocotlán de Morelos', 20),
					('Puerto Escondido', 20),
					('Putla Villa de Guerrero', 20),
					('Río Grande o Piedra Parada', 20),
					('Salina Cruz', 20),
					('San Antonio de la Cal', 20),
					('San Blas Atempa', 20),
					('San Felipe Jalapa de Díaz', 20),
					('San Francisco Ixhuatán', 20),
					('San Francisco Telixtlahuaca', 20),
					('San Juan Bautista Cuicatlán', 20),
					('San Juan Bautista lo de Soto', 20),
					('San Juan Bautista Tuxtepec', 20),
					('San Juan Bautista Valle Nacional', 20),
					('San Juan Cacahuatepec', 20),
					('San Miguel el Grande', 20),
					('San Pablo Huitzo', 20),
					('San Pablo Villa de Mitla', 20),
					('San Pedro Mixtepec -Dto. 22-', 20),
					('San Pedro Pochutla', 20),
					('San Pedro Tapanatepec', 20),
					('San Pedro Totolapa', 20),
					('San Sebastián Tecomaxtlahuaca', 20),
					('Santa Cruz Itundujia', 20),
					('Santa Lucia del Camino', 20),
					('Santa María Huatulco', 20),
					('Santiago Jamiltepec', 20),
					('Santiago Juxtlahuaca', 20),
					('Santiago Pinotepa Nacional', 20),
					('Santiago Suchilquitongo', 20),
					('Santo Domingo Tehuantepec', 20),
					('Teotitlán de Flores Magón', 20),
					('Tlacolula de Matamoros', 20),
					('Unión Hidalgo', 20),
					('Vicente Camalote', 20),
					('Villa de Tamazulápam del Progreso', 20),
					('Villa de Zaachila', 20),
					('Villa Sola de Vega', 20),
					('Zimatlán de Álvarez', 20),
					('Acatlán de Osorio', 21),
					('Amozoc', 21),
					('Atlixco', 21),
					('Ciudad Serdán', 21),
					('Cuautlancingo', 21),
					('Huauchinango', 21),
					('Izúcar de Matamoros', 21),
					('NO_DATA', 21),
					('Puebla (Heroica Puebla)', 21),
					('San Andrés Cholula', 21),
					('San Martín Texmelucan de Labastida', 21),
					('San Pedro Cholula', 21),
					('Tecamachalco', 21),
					('Tehuacan', 21),
					('Tepeaca', 21),
					('Teziutlan', 21),
					('Xicotepec', 21),
					('Zacatlán', 21),
					('El Pueblito', 22),
					('NO_DATA', 22),
					('Querétaro', 22),
					('San Juan del Rio', 22),
					('Bacalar', 23),
					('Cancún', 23),
					('Chetumal', 23),
					('Cozumel', 23),
					('Felipe Carrillo Puerto', 23),
					('Isla Mujeres', 23),
					('Kantunilkín', 23),
					('NO_DATA', 23),
					('Playa del Carmen', 23),
					('Cárdenas', 24),
					('Cedral', 24),
					('Cerritos', 24),
					('Charcas', 24),
					('Ciudad del Maíz', 24),
					('Ciudad Valles', 24),
					('Ébano', 24),
					('El Naranjo', 24),
					('Fracción el Refugio', 24),
					('Matehuala', 24),
					('NO_DATA', 24),
					('Rioverde', 24),
					('Salinas de Hidalgo', 24),
					('San Luis Potosí', 24),
					('Santa María del Río', 24),
					('Soledad de Graciano Sánchez', 24),
					('Tamasopo', 24),
					('Tamazunchale', 24),
					('Tamuin', 24),
					('Tierra Nueva', 24),
					('Villa de Reyes', 24),
					('Aguaruto', 25),
					('Ahome', 25),
					('Angostura', 25),
					('Choix', 25),
					('Cosalá', 25),
					('Culiacán Rosales', 25),
					('El rosario', 25),
					('Escuinapa de Hidalgo', 25),
					('Estación Naranjo', 25),
					('Guamáchil', 25),
					('Guasave', 25),
					('Higuera de Zaragoza', 25),
					('La Cruz', 25),
					('Lic. Benito Juárez (Campo Gobierno)', 25),
					('Los Mochis', 25),
					('Mazatlán', 25),
					('Mocorito', 25),
					('Navolato', 25),
					('NO_DATA', 25),
					('Quila', 25),
					('San Blas', 25),
					('San Ignacio', 25),
					('Sinaloa de Leyva', 25),
					('Topolobampo', 25),
					('Villa Unión', 25),
					('Agua Prieta', 26),
					('Ciudad Obregón', 26),
					('Empalme', 26),
					('Hermosillo', 26),
					('Heroica Caborca', 26),
					('Heroica Ciudad de Cananea', 26),
					('Heroica Guaymas', 26),
					('Heroica Nogales', 26),
					('Huatabampo', 26),
					('Magdalena de Kino', 26),
					('Navojoa', 26),
					('NO_DATA', 26),
					('Puerto Peñasco', 26),
					('San Luis Río Colorado', 26),
					('Sonoita', 26),
					('Cárdenas', 27),
					('Comalcalco', 27),
					('Cunduac�n', 27),
					('Emiliano Zapata', 27),
					('Frontera', 27),
					('Huimanguillo', 27),
					('Jalpa de Méndez', 27),
					('Macuspana', 27),
					('NO_DATA', 27),
					('Paraíso', 27),
					('Teapa', 27),
					('Tenosique de Pino Suárez', 27),
					('Villahermosa', 27),
					('Altamira', 28),
					('Ciudad Camargo', 28),
					('Ciudad Gustavo Dáaz Ordaz', 28),
					('Ciudad Madero', 28),
					('Ciudad Mante', 28),
					('Ciudad Miguel Alemán', 28),
					('Ciudad Río Bravo', 28),
					('Ciudad Tula', 28),
					('Ciudad Victoria', 28),
					('Estación Manuel (Úrsulo Galván)', 28),
					('González', 28),
					('Heroica Matamoros', 28),
					('Jaumave', 28),
					('NO_DATA', 28),
					('Nueva Ciudad Guerrero', 28),
					('Nuevo Laredo', 28),
					('Reynosa', 28),
					('San Fernando', 28),
					('Soto la Marina', 28),
					('Tampico', 28),
					('Valle Hermoso', 28),
					('Xicotáncatl', 28),
					('Apizaco', 29),
					('Calpulalpan', 29),
					('Chiautempan', 29),
					('Huamantla', 29),
					('NO_DATA', 29),
					('Tlaxcala (Tlaxcala de Xicotencatl)', 29),
					('Villa Vicente Guerrero', 29),
					('Acayucan', 30),
					('Agua dulce', 30),
					('Altotonga', 30),
					('Alvarado', 30),
					('Ángel R. Cabada', 30),
					('Atoyac', 30),
					('Banderilla', 30),
					('Boca del Río', 30),
					('Carlos A. Carrillo', 30),
					('Catemaco', 30),
					('Cazones de Herrera', 30),
					('Cerro Azul', 30),
					('Coatepec', 30),
					('Coatzacoalcos', 30),
					('Coatzintla', 30),
					('Córdoba', 30),
					('Cosamaloapan', 30),
					('Cosoleacaque', 30),
					('Cuichapa', 30),
					('Cuitláhuac', 30),
					('El Higo', 30),
					('Fortón de las Flores', 30),
					('General Miguel Alemán (Potrero Nuevo)', 30),
					('Gutiérrez Zamora', 30),
					('Huatusco de Chicuellar', 30),
					('Huayacocotla', 30),
					('Huiloapan de Cuauhtémoc', 30),
					('Isla', 30),
					('Ixtaczoquitlán', 30),
					('Jáltipan de Morelos', 30),
					('José Cardel', 30),
					('Juan Dáaz Covarrubias', 30),
					('Juan Rodríguez Clara', 30),
					('Las Choapas', 30),
					('Lerdo de Tejada', 30),
					('Minatitlán', 30),
					('Naranjos', 30),
					('Nogales', 30),
					('NO_DATA', 30),
					('Orizaba', 30),
					('Pánuco', 30),
					('Papantla de Olarte', 30),
					('Paraje Nuevo', 30),
					('Paso de Ovejas', 30),
					('Paso del Macho', 30),
					('Platón Sánchez', 30),
					('Playa Vicente', 30),
					('Poza Rica de Hidalgo', 30),
					('Río Blanco', 30),
					('San Andrés Tuxtla', 30),
					('San Rafael', 30),
					('Santiago Tuxtla', 30),
					('Sihuapan', 30),
					('Soledad de Doblado', 30),
					('Tampico Alto', 30),
					('Tantoyuca', 30),
					('Tempoal de Sánchez', 30),
					('Tezonapa', 30),
					('Tierra Blanca', 30),
					('Tihuatlán', 30),
					('Tlacojalpan', 30),
					('Tlapacoyan', 30),
					('Tres Valles', 30),
					('Túxpam de Rodríguez Cano', 30),
					('Veracruz', 30),
					('Xalapa-Enríquez', 30),
					('Yecuatla', 30),
					('Kanasín', 31),
					('Mérida', 31),
					('Motul de Carrillo Puerto', 31),
					('NO_DATA', 31),
					('Ticul', 31),
					('Tizimín', 31),
					('Valladolid', 31),
					('Ciudad Cuauhtémoc', 32),
					('Fresnillo', 32),
					('Guadalupe', 32),
					('Jalpa', 32),
					('Jerez de García Salinas', 32),
					('Juan Aldama', 32),
					('Loreto', 32),
					('Luis Moya', 32),
					('Moyahua de Estrada', 32),
					('Nochistlán de Mejía', 32),
					('NO_DATA', 32),
					('Ojocaliente', 32),
					('Río Grande', 32),
					('Sombrerete', 32),
					('Valparaíso', 32),
					('Víctor Rosales', 32),
					('Villa de Cos', 32),
					('Villa Hidalgo', 32),
					('Villanueva', 32),
					('Zacatecas', 32)");
    }
}
