<?php

use Illuminate\Database\Seeder;

class CountryTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::insert("REPLACE INTO country (id, created_at, created_by, status, updated_at, updated_by, code, country_name) VALUES 
					(1,NULL,'eduApi','A',NULL,'eduApi','AA','Aruba'),
					(2,NULL,'eduApi','A',NULL,'eduApi','AC','Antigua and Barbuda'),
					(3,NULL,'eduApi','A',NULL,'eduApi','AE','United Arab Emirates'),
					(4,NULL,'eduApi','A',NULL,'eduApi','AF','Afghanistan'),
					(5,NULL,'eduApi','A',NULL,'eduApi','AG','Algeria'),
					(6,NULL,'eduApi','A',NULL,'eduApi','AJ','Azerbaijan'),
					(7,NULL,'eduApi','A',NULL,'eduApi','AL','Albania'),
					(8,NULL,'eduApi','A',NULL,'eduApi','AM','Armenia'),
					(9,NULL,'eduApi','A',NULL,'eduApi','AN','Andorra'),
					(10,NULL,'eduApi','A',NULL,'eduApi','AO','Angola'),
					(11,NULL,'eduApi','A',NULL,'eduApi','AQ','American Samoa'),
					(12,NULL,'eduApi','A',NULL,'eduApi','AR','Argentina'),
					(13,NULL,'eduApi','A',NULL,'eduApi','AS','Australia'),
					(14,NULL,'eduApi','A',NULL,'eduApi','AT','Ashmore and Cartier Islands'),
					(15,NULL,'eduApi','A',NULL,'eduApi','AU','Austria'),
					(16,NULL,'eduApi','A',NULL,'eduApi','AV','Anguilla'),
					(17,NULL,'eduApi','A',NULL,'eduApi','AX','Åland Islands'),
					(18,NULL,'eduApi','A',NULL,'eduApi','AY','Antarctica'),
					(19,NULL,'eduApi','A',NULL,'eduApi','BA','Bahrain'),
					(20,NULL,'eduApi','A',NULL,'eduApi','BB','Barbados'),
					(21,NULL,'eduApi','A',NULL,'eduApi','BC','Botswana'),
					(22,NULL,'eduApi','A',NULL,'eduApi','BD','Bermuda'),
					(23,NULL,'eduApi','A',NULL,'eduApi','BE','Belgium'),
					(24,NULL,'eduApi','A',NULL,'eduApi','BF','Bahamas, The'),
					(25,NULL,'eduApi','A',NULL,'eduApi','BG','Bangladesh'),
					(26,NULL,'eduApi','A',NULL,'eduApi','BH','Belize'),
					(27,NULL,'eduApi','A',NULL,'eduApi','BK','Bosnia and Herzegovina'),
					(28,NULL,'eduApi','A',NULL,'eduApi','BL','Bolivia'),
					(29,NULL,'eduApi','A',NULL,'eduApi','BM','Myanmar'),
					(30,NULL,'eduApi','A',NULL,'eduApi','BN','Benin'),
					(31,NULL,'eduApi','A',NULL,'eduApi','BO','Belarus'),
					(32,NULL,'eduApi','A',NULL,'eduApi','BP','Solomon Islands'),
					(33,NULL,'eduApi','A',NULL,'eduApi','BQ','Navassa Island'),
					(34,NULL,'eduApi','A',NULL,'eduApi','BR','Brazil'),
					(35,NULL,'eduApi','A',NULL,'eduApi','BS','Bassas da India'),
					(36,NULL,'eduApi','A',NULL,'eduApi','BT','Bhutan'),
					(37,NULL,'eduApi','A',NULL,'eduApi','BU','Bulgaria'),
					(38,NULL,'eduApi','A',NULL,'eduApi','BV','Bouvet Island'),
					(39,NULL,'eduApi','A',NULL,'eduApi','BX','Brunei'),
					(40,NULL,'eduApi','A',NULL,'eduApi','BY','Burundi'),
					(41,NULL,'eduApi','A',NULL,'eduApi','CA','Canada'),
					(42,NULL,'eduApi','A',NULL,'eduApi','CB','Cambodia'),
					(43,NULL,'eduApi','A',NULL,'eduApi','CD','Chad'),
					(44,NULL,'eduApi','A',NULL,'eduApi','CE','Sri Lanka'),
					(45,NULL,'eduApi','A',NULL,'eduApi','CF','Congo, Republic of the'),
					(46,NULL,'eduApi','A',NULL,'eduApi','CG','Congo, Democratic Republic of the'),
					(47,NULL,'eduApi','A',NULL,'eduApi','CH','China'),
					(48,NULL,'eduApi','A',NULL,'eduApi','CI','Chile'),
					(49,NULL,'eduApi','A',NULL,'eduApi','CJ','Cayman Islands'),
					(50,NULL,'eduApi','A',NULL,'eduApi','CK','Cocos (Keeling) Islands'),
					(51,NULL,'eduApi','A',NULL,'eduApi','CM','Cameroon'),
					(52,NULL,'eduApi','A',NULL,'eduApi','CN','Comoros'),
					(53,NULL,'eduApi','A',NULL,'eduApi','CO','Colombia'),
					(54,NULL,'eduApi','A',NULL,'eduApi','CQ','Northern Mariana Islands'),
					(55,NULL,'eduApi','A',NULL,'eduApi','CR','Coral Sea Islands'),
					(56,NULL,'eduApi','A',NULL,'eduApi','CS','Costa Rica'),
					(57,NULL,'eduApi','A',NULL,'eduApi','CT','Central African Republic'),
					(58,NULL,'eduApi','A',NULL,'eduApi','CU','Cuba'),
					(59,NULL,'eduApi','A',NULL,'eduApi','CV','Cape Verde'),
					(60,NULL,'eduApi','A',NULL,'eduApi','CW','Cook Islands'),
					(61,NULL,'eduApi','A',NULL,'eduApi','CY','Cyprus'),
					(62,NULL,'eduApi','A',NULL,'eduApi','DA','Denmark'),
					(63,NULL,'eduApi','A',NULL,'eduApi','DJ','Djibouti'),
					(64,NULL,'eduApi','A',NULL,'eduApi','DO','Dominica'),
					(65,NULL,'eduApi','A',NULL,'eduApi','DQ','Jarvis Island'),
					(66,NULL,'eduApi','A',NULL,'eduApi','DR','Dominican Republic'),
					(67,NULL,'eduApi','A',NULL,'eduApi','DX','Dhekelia Sovereign Base Area'),
					(68,NULL,'eduApi','A',NULL,'eduApi','EC','Ecuador'),
					(69,NULL,'eduApi','A',NULL,'eduApi','EG','Egypt'),
					(70,NULL,'eduApi','A',NULL,'eduApi','EI','Ireland'),
					(71,NULL,'eduApi','A',NULL,'eduApi','EK','Equatorial Guinea'),
					(72,NULL,'eduApi','A',NULL,'eduApi','EN','Estonia'),
					(73,NULL,'eduApi','A',NULL,'eduApi','ER','Eritrea'),
					(74,NULL,'eduApi','A',NULL,'eduApi','ES','El Salvador'),
					(75,NULL,'eduApi','A',NULL,'eduApi','ET','Ethiopia'),
					(76,NULL,'eduApi','A',NULL,'eduApi','EU','Europa Island'),
					(77,NULL,'eduApi','A',NULL,'eduApi','EZ','Czech Republic'),
					(78,NULL,'eduApi','A',NULL,'eduApi','FG','French Guiana'),
					(79,NULL,'eduApi','A',NULL,'eduApi','FI','Finland'),
					(80,NULL,'eduApi','A',NULL,'eduApi','FJ','Fiji'),
					(81,NULL,'eduApi','A',NULL,'eduApi','FK','Falkland Islands (Islas Malvinas)'),
					(82,NULL,'eduApi','A',NULL,'eduApi','FM','Micronesia, Federated States of'),
					(83,NULL,'eduApi','A',NULL,'eduApi','FO','Faroe Islands'),
					(84,NULL,'eduApi','A',NULL,'eduApi','FP','French Polynesia'),
					(85,NULL,'eduApi','A',NULL,'eduApi','FQ','Baker Island'),
					(86,NULL,'eduApi','A',NULL,'eduApi','FR','France'),
					(87,NULL,'eduApi','A',NULL,'eduApi','FS','French Southern and Antarctic Lands'),
					(88,NULL,'eduApi','A',NULL,'eduApi','GA','Gambia, The'),
					(89,NULL,'eduApi','A',NULL,'eduApi','GB','Gabon'),
					(90,NULL,'eduApi','A',NULL,'eduApi','GG','Georgia'),
					(91,NULL,'eduApi','A',NULL,'eduApi','GH','Ghana'),
					(92,NULL,'eduApi','A',NULL,'eduApi','GI','Gibraltar'),
					(93,NULL,'eduApi','A',NULL,'eduApi','GJ','Grenada'),
					(94,NULL,'eduApi','A',NULL,'eduApi','GK','Guernsey'),
					(95,NULL,'eduApi','A',NULL,'eduApi','GL','Greenland'),
					(96,NULL,'eduApi','A',NULL,'eduApi','GM','Germany'),
					(97,NULL,'eduApi','A',NULL,'eduApi','GO','Glorioso Islands'),
					(98,NULL,'eduApi','A',NULL,'eduApi','GP','Guadeloupe'),
					(99,NULL,'eduApi','A',NULL,'eduApi','GQ','Guam'),
					(100,NULL,'eduApi','A',NULL,'eduApi','GR','Greece'),
					(101,NULL,'eduApi','A',NULL,'eduApi','GT','Guatemala'),
					(102,NULL,'eduApi','A',NULL,'eduApi','GV','Guinea'),
					(103,NULL,'eduApi','A',NULL,'eduApi','GY','Guyana'),
					(104,NULL,'eduApi','A',NULL,'eduApi','GZ','Gaza Strip'),
					(105,NULL,'eduApi','A',NULL,'eduApi','HA','Haiti'),
					(106,NULL,'eduApi','A',NULL,'eduApi','HK','Hong Kong'),
					(107,NULL,'eduApi','A',NULL,'eduApi','HM','Heard Island and McDonald Islands'),
					(108,NULL,'eduApi','A',NULL,'eduApi','HO','Honduras'),
					(109,NULL,'eduApi','A',NULL,'eduApi','HQ','Howland Island'),
					(110,NULL,'eduApi','A',NULL,'eduApi','HR','Croatia'),
					(111,NULL,'eduApi','A',NULL,'eduApi','HU','Hungary'),
					(112,NULL,'eduApi','A',NULL,'eduApi','IC','Iceland'),
					(113,NULL,'eduApi','A',NULL,'eduApi','ID','Indonesia'),
					(114,NULL,'eduApi','A',NULL,'eduApi','IM','Isle of Man'),
					(115,NULL,'eduApi','A',NULL,'eduApi','IN','India'),
					(116,NULL,'eduApi','A',NULL,'eduApi','IO','British Indian Ocean Territory'),
					(117,NULL,'eduApi','A',NULL,'eduApi','IP','Clipperton Island'),
					(118,NULL,'eduApi','A',NULL,'eduApi','IR','Iran'),
					(119,NULL,'eduApi','A',NULL,'eduApi','IS','Israel'),
					(120,NULL,'eduApi','A',NULL,'eduApi','IT','Italy'),
					(121,NULL,'eduApi','A',NULL,'eduApi','IV','Cote d\'Ivoire'),
					(122,NULL,'eduApi','A',NULL,'eduApi','IZ','Iraq'),
					(123,NULL,'eduApi','A',NULL,'eduApi','JA','Japan'),
					(124,NULL,'eduApi','A',NULL,'eduApi','JE','Jersey'),
					(125,NULL,'eduApi','A',NULL,'eduApi','JM','Jamaica'),
					(126,NULL,'eduApi','A',NULL,'eduApi','JN','Jan Mayen'),
					(127,NULL,'eduApi','A',NULL,'eduApi','JO','Jordan'),
					(128,NULL,'eduApi','A',NULL,'eduApi','JQ','Johnston Atoll'),
					(129,NULL,'eduApi','A',NULL,'eduApi','JU','Juan de Nova Island'),
					(130,NULL,'eduApi','A',NULL,'eduApi','KE','Kenya'),
					(131,NULL,'eduApi','A',NULL,'eduApi','KG','Kyrgyzstan'),
					(132,NULL,'eduApi','A',NULL,'eduApi','KN','Korea, North'),
					(133,NULL,'eduApi','A',NULL,'eduApi','KQ','Kingman Reef'),
					(134,NULL,'eduApi','A',NULL,'eduApi','KR','Kiribati'),
					(135,NULL,'eduApi','A',NULL,'eduApi','KS','Korea, South'),
					(136,NULL,'eduApi','A',NULL,'eduApi','KT','Christmas Island'),
					(137,NULL,'eduApi','A',NULL,'eduApi','KU','Kuwait'),
					(138,NULL,'eduApi','A',NULL,'eduApi','KV','Kosovo'),
					(139,NULL,'eduApi','A',NULL,'eduApi','KZ','Kazakhstan'),
					(140,NULL,'eduApi','A',NULL,'eduApi','LA','Laos'),
					(141,NULL,'eduApi','A',NULL,'eduApi','LE','Lebanon'),
					(142,NULL,'eduApi','A',NULL,'eduApi','LG','Latvia'),
					(143,NULL,'eduApi','A',NULL,'eduApi','LH','Lithuania'),
					(144,NULL,'eduApi','A',NULL,'eduApi','LI','Liberia'),
					(145,NULL,'eduApi','A',NULL,'eduApi','LO','Slovakia'),
					(146,NULL,'eduApi','A',NULL,'eduApi','LQ','Palmyra Atoll'),
					(147,NULL,'eduApi','A',NULL,'eduApi','LS','Liechtenstein'),
					(148,NULL,'eduApi','A',NULL,'eduApi','LT','Lesotho'),
					(149,NULL,'eduApi','A',NULL,'eduApi','LU','Luxembourg'),
					(150,NULL,'eduApi','A',NULL,'eduApi','LY','Libyan Arab'),
					(151,NULL,'eduApi','A',NULL,'eduApi','MA','Madagascar'),
					(152,NULL,'eduApi','A',NULL,'eduApi','MB','Martinique'),
					(153,NULL,'eduApi','A',NULL,'eduApi','MC','Macau'),
					(154,NULL,'eduApi','A',NULL,'eduApi','MD','Moldova, Republic of'),
					(155,NULL,'eduApi','A',NULL,'eduApi','MF','Mayotte'),
					(156,NULL,'eduApi','A',NULL,'eduApi','MG','Mongolia'),
					(157,NULL,'eduApi','A',NULL,'eduApi','MH','Montserrat'),
					(158,NULL,'eduApi','A',NULL,'eduApi','MI','Malawi'),
					(159,NULL,'eduApi','A',NULL,'eduApi','MJ','Montenegro'),
					(160,NULL,'eduApi','A',NULL,'eduApi','MK','The Former Yugoslav Republic of Macedonia'),
					(161,NULL,'eduApi','A',NULL,'eduApi','ML','Mali'),
					(162,NULL,'eduApi','A',NULL,'eduApi','MN','Monaco'),
					(163,NULL,'eduApi','A',NULL,'eduApi','MO','Morocco'),
					(164,NULL,'eduApi','A',NULL,'eduApi','MP','Mauritius'),
					(165,NULL,'eduApi','A',NULL,'eduApi','MQ','Midway Islands'),
					(166,NULL,'eduApi','A',NULL,'eduApi','MR','Mauritania'),
					(167,NULL,'eduApi','A',NULL,'eduApi','MT','Malta'),
					(168,NULL,'eduApi','A',NULL,'eduApi','MU','Oman'),
					(169,NULL,'eduApi','A',NULL,'eduApi','MV','Maldives'),
					(170,NULL,'eduApi','A',NULL,'eduApi','MX','México'),
					(171,NULL,'eduApi','A',NULL,'eduApi','MY','Malaysia'),
					(172,NULL,'eduApi','A',NULL,'eduApi','MZ','Mozambique'),
					(173,NULL,'eduApi','A',NULL,'eduApi','NC','New Caledonia'),
					(174,NULL,'eduApi','A',NULL,'eduApi','NE','Niue'),
					(175,NULL,'eduApi','A',NULL,'eduApi','NF','Norfolk Island'),
					(176,NULL,'eduApi','A',NULL,'eduApi','NG','Niger'),
					(177,NULL,'eduApi','A',NULL,'eduApi','NH','Vanuatu'),
					(178,NULL,'eduApi','A',NULL,'eduApi','NI','Nigeria'),
					(179,NULL,'eduApi','A',NULL,'eduApi','NL','Netherlands'),
					(180,NULL,'eduApi','A',NULL,'eduApi','NM','No Man\'s Land'),
					(181,NULL,'eduApi','A',NULL,'eduApi','NO','Norway'),
					(182,NULL,'eduApi','A',NULL,'eduApi','NP','Nepal'),
					(183,NULL,'eduApi','A',NULL,'eduApi','NR','Nauru'),
					(184,NULL,'eduApi','A',NULL,'eduApi','NS','Suriname'),
					(185,NULL,'eduApi','A',NULL,'eduApi','NT','Netherlands Antilles'),
					(186,NULL,'eduApi','A',NULL,'eduApi','NU','Nicaragua'),
					(187,NULL,'eduApi','A',NULL,'eduApi','NZ','New Zealand'),
					(188,NULL,'eduApi','A',NULL,'eduApi','PA','Paraguay'),
					(189,NULL,'eduApi','A',NULL,'eduApi','PC','Pitcairn Islands'),
					(190,NULL,'eduApi','A',NULL,'eduApi','PE','Peru'),
					(191,NULL,'eduApi','A',NULL,'eduApi','PF','Paracel Islands'),
					(192,NULL,'eduApi','A',NULL,'eduApi','PG','Spratly Islands'),
					(193,NULL,'eduApi','A',NULL,'eduApi','PK','Pakistan'),
					(194,NULL,'eduApi','A',NULL,'eduApi','PL','Poland'),
					(195,NULL,'eduApi','A',NULL,'eduApi','PM','Panama'),
					(196,NULL,'eduApi','A',NULL,'eduApi','PO','Portugal'),
					(197,NULL,'eduApi','A',NULL,'eduApi','PP','Papua New Guinea'),
					(198,NULL,'eduApi','A',NULL,'eduApi','PS','Palau'),
					(199,NULL,'eduApi','A',NULL,'eduApi','PU','Guinea-Bissau'),
					(200,NULL,'eduApi','A',NULL,'eduApi','QA','Qatar'),
					(201,NULL,'eduApi','A',NULL,'eduApi','RE','Reunion'),
					(202,NULL,'eduApi','A',NULL,'eduApi','RI','Serbia'),
					(203,NULL,'eduApi','A',NULL,'eduApi','RM','Marshall Islands'),
					(204,NULL,'eduApi','A',NULL,'eduApi','RN','Saint Martin'),
					(205,NULL,'eduApi','A',NULL,'eduApi','RO','Romania'),
					(206,NULL,'eduApi','A',NULL,'eduApi','RP','Philippines'),
					(207,NULL,'eduApi','A',NULL,'eduApi','RQ','Puerto Rico'),
					(208,NULL,'eduApi','A',NULL,'eduApi','RS','Russia'),
					(209,NULL,'eduApi','A',NULL,'eduApi','RW','Rwanda'),
					(210,NULL,'eduApi','A',NULL,'eduApi','SA','Saudi Arabia'),
					(211,NULL,'eduApi','A',NULL,'eduApi','SB','Saint Pierre and Miquelon'),
					(212,NULL,'eduApi','A',NULL,'eduApi','SC','Saint Kitts and Nevis'),
					(213,NULL,'eduApi','A',NULL,'eduApi','SE','Seychelles'),
					(214,NULL,'eduApi','A',NULL,'eduApi','SF','South Africa'),
					(215,NULL,'eduApi','A',NULL,'eduApi','SG','Senegal'),
					(216,NULL,'eduApi','A',NULL,'eduApi','SH','Saint Helena'),
					(217,NULL,'eduApi','A',NULL,'eduApi','SI','Slovenia'),
					(218,NULL,'eduApi','A',NULL,'eduApi','SL','Sierra Leone'),
					(219,NULL,'eduApi','A',NULL,'eduApi','SM','San Marino'),
					(220,NULL,'eduApi','A',NULL,'eduApi','SN','Singapore'),
					(221,NULL,'eduApi','A',NULL,'eduApi','SO','Somalia'),
					(222,NULL,'eduApi','A',NULL,'eduApi','SP','Spain'),
					(223,NULL,'eduApi','A',NULL,'eduApi','ST','Saint Lucia'),
					(224,NULL,'eduApi','A',NULL,'eduApi','SU','Sudan'),
					(225,NULL,'eduApi','A',NULL,'eduApi','SV','Svalbard'),
					(226,NULL,'eduApi','A',NULL,'eduApi','SW','Sweden'),
					(227,NULL,'eduApi','A',NULL,'eduApi','SX','South Georgia and the Islands'),
					(228,NULL,'eduApi','A',NULL,'eduApi','SY','Syrian Arab Republic'),
					(229,NULL,'eduApi','A',NULL,'eduApi','SZ','Switzerland'),
					(230,NULL,'eduApi','A',NULL,'eduApi','TD','Trinidad and Tobago'),
					(231,NULL,'eduApi','A',NULL,'eduApi','TE','Tromelin Island'),
					(232,NULL,'eduApi','A',NULL,'eduApi','TH','Thailand'),
					(233,NULL,'eduApi','A',NULL,'eduApi','TI','Tajikistan'),
					(234,NULL,'eduApi','A',NULL,'eduApi','TK','Turks and Caicos Islands'),
					(235,NULL,'eduApi','A',NULL,'eduApi','TL','Tokelau'),
					(236,NULL,'eduApi','A',NULL,'eduApi','TN','Tonga'),
					(237,NULL,'eduApi','A',NULL,'eduApi','TO','Togo'),
					(238,NULL,'eduApi','A',NULL,'eduApi','TP','Sao Tome and Principe'),
					(239,NULL,'eduApi','A',NULL,'eduApi','TS','Tunisia'),
					(240,NULL,'eduApi','A',NULL,'eduApi','TT','East Timor'),
					(241,NULL,'eduApi','A',NULL,'eduApi','TU','Turkey'),
					(242,NULL,'eduApi','A',NULL,'eduApi','TV','Tuvalu'),
					(243,NULL,'eduApi','A',NULL,'eduApi','TW','Taiwan'),
					(244,NULL,'eduApi','A',NULL,'eduApi','TX','Turkmenistan'),
					(245,NULL,'eduApi','A',NULL,'eduApi','TZ','Tanzania, United Republic of'),
					(246,NULL,'eduApi','A',NULL,'eduApi','UG','Uganda'),
					(247,NULL,'eduApi','A',NULL,'eduApi','UK','United Kingdom'),
					(248,NULL,'eduApi','A',NULL,'eduApi','UP','Ukraine'),
					(249,NULL,'eduApi','A',NULL,'eduApi','US','United States'),
					(250,NULL,'eduApi','A',NULL,'eduApi','UV','Burkina Faso'),
					(251,NULL,'eduApi','A',NULL,'eduApi','UY','Uruguay'),
					(252,NULL,'eduApi','A',NULL,'eduApi','UZ','Uzbekistan'),
					(253,NULL,'eduApi','A',NULL,'eduApi','VC','Saint Vincent and the Grenadines'),
					(254,NULL,'eduApi','A',NULL,'eduApi','VE','Venezuela'),
					(255,NULL,'eduApi','A',NULL,'eduApi','VI','British Virgin Islands'),
					(256,NULL,'eduApi','A',NULL,'eduApi','VM','Vietnam'),
					(257,NULL,'eduApi','A',NULL,'eduApi','VQ','Virgin Islands (US)'),
					(258,NULL,'eduApi','A',NULL,'eduApi','VT','Holy See (Vatican City)'),
					(259,NULL,'eduApi','A',NULL,'eduApi','WA','Namibia'),
					(260,NULL,'eduApi','A',NULL,'eduApi','WE','West Bank'),
					(261,NULL,'eduApi','A',NULL,'eduApi','WF','Wallis and Futuna'),
					(262,NULL,'eduApi','A',NULL,'eduApi','WI','Western Sahara'),
					(263,NULL,'eduApi','A',NULL,'eduApi','WQ','Wake Island'),
					(264,NULL,'eduApi','A',NULL,'eduApi','WS','Samoa'),
					(265,NULL,'eduApi','A',NULL,'eduApi','WZ','Swaziland'),
					(266,NULL,'eduApi','A',NULL,'eduApi','YI','Serbia and Montenegro'),
					(267,NULL,'eduApi','A',NULL,'eduApi','YM','Yemen'),
					(268,NULL,'eduApi','A',NULL,'eduApi','ZA','Zambia'),
					(269,NULL,'eduApi','A',NULL,'eduApi','ZI','Zimbabwe')");
    }
}
