<?php

use Illuminate\Database\Seeder;

class MunicipalityTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::insert("REPLACE INTO municipality (description, state_id) VALUES 
					('Aguascalientes', 1),
					('Asientos', 1),
					('San José de Gracia', 1),
					('El Llano', 1),
					('Jesús María', 1),
					('Pabellón de Arteaga', 1),
					('Cos�o', 1),
					('San Francisco de los Romo', 1),
					('Calvillo', 1),
					('Tepezal�', 1),
					('Rincón de Romos', 1),
					('Tijuana', 2),
					('Ensenada', 2),
					('Tecate', 2),
					('Playas de Rosarito', 2),
					('Mexicali', 2),
					('La Paz', 3),
					('Comond�', 3),
					('Muleg�', 3),
					('Los Cabos', 3),
					('Loreto', 3),
					('Candelaria', 4),
					('Tenabo', 4),
					('Campeche', 4),
					('Champotón', 4),
					('Calkin�', 4),
					('Palizada', 4),
					('Calakmul', 4),
					('Escárcega', 4),
					('Hecelchak�n', 4),
					('Carmen', 4),
					('Hopelch�n', 4),
					('Saltillo', 5),
					('Frontera', 5),
					('M�zquiz', 5),
					('Sabinas', 5),
					('Cuatro Ciénegas', 5),
					('San Buenaventura', 5),
					('Piedras Negras', 5),
					('Villa Unión', 5),
					('Ocampo', 5),
					('Parras', 5),
					('Juárez', 5),
					('Casta�os', 5),
					('Zaragoza', 5),
					('Torreón', 5),
					('Sacramento', 5),
					('Candela', 5),
					('Acuña', 5),
					('Hidalgo', 5),
					('Sierra Mojada', 5),
					('Escobedo', 5),
					('General Cepeda', 5),
					('Allende', 5),
					('Viesca', 5),
					('Francisco I. Madero', 5),
					('Arteaga', 5),
					('Monclova', 5),
					('Jiménez', 5),
					('San Juan de Sabinas', 5),
					('Lamadrid', 5),
					('Abasolo', 5),
					('Nava', 5),
					('Guerrero', 5),
					('Nadadores', 5),
					('Progreso', 5),
					('Ramos Arizpe', 5),
					('Morelos', 5),
					('Matamoros', 5),
					('San Pedro', 5),
					('Manzanillo', 6),
					('Ixtlahuac�n', 6),
					('Coquimatl�n', 6),
					('Tecomán', 6),
					('Villa de Álvarez', 6),
					('Cuauhtémoc', 6),
					('Armería', 6),
					('Colima', 6),
					('Minatitl�n', 6),
					('Comala', 6),
					('Tuxtla Gutiérrez', 7),
					('Chamula', 7),
					('Chanal', 7),
					('Sunuapa', 7),
					('Chicoas�n', 7),
					('Ixhuat�n', 7),
					('Sabanilla', 7),
					('Aldama', 7),
					('Chil�n', 7),
					('Chicomuselo', 7),
					('Venustiano Carranza', 7),
					('Cintalapa', 7),
					('Acapetahua', 7),
					('Tapachula', 7),
					('Mazapa de Madero', 7),
					('Chiapa de Corzo', 7),
					('San Lucas', 7),
					('Reforma', 7),
					('Ixtapangajoya', 7),
					('Chapultenango', 7),
					('Bochil', 7),
					('Larr�inzar', 7),
					('Tumbal�', 7),
					('Catazaj�', 7),
					('Maravilla Tenejapa', 7),
					('Angel Albino Corzo', 7),
					('Villa Corzo', 7),
					('Mazat�n', 7),
					('Unión Juárez', 7),
					('Siltepec', 7),
					('Berrioz�bal', 7),
					('Zinacant�n', 7),
					('Huixt�n', 7),
					('Francisco Le�n', 7),
					('Pantepec', 7),
					('Ray�n', 7),
					('San Andrés Duraznal', 7),
					('Sital�', 7),
					('Marqu�s de Comillas', 7),
					('Frontera Comalapa', 7),
					('Nicolás Ru�z', 7),
					('Arriaga', 7),
					('Escuintla', 7),
					('Frontera Hidalgo', 7),
					('Bejucal de Ocampo', 7),
					('San Cristóbal de las Casas', 7),
					('Amatenango del Valle', 7),
					('Pichucalco', 7),
					('Copainal�', 7),
					('Huitiup�n', 7),
					('San Juan Cancuc', 7),
					('Chenalh�', 7),
					('Ocosingo', 7),
					('Tzimol', 7),
					('Altamirano', 7),
					('Socoltenango', 7),
					('Mapastepec', 7),
					('Tuzant�n', 7),
					('Motozintla', 7),
					('Suchiapa', 7),
					('Chiapilla', 7),
					('Mitontic', 7),
					('Solosuchiapa', 7),
					('Ocotepec', 7),
					('Jitotol', 7),
					('Chalchihuit�n', 7),
					('Tila', 7),
					('La Libertad', 7),
					('La Independencia', 7),
					('La Concordia', 7),
					('Tonalá', 7),
					('Huixtla', 7),
					('Tuxtla Chico', 7),
					('El Porvenir', 7),
					('San Fernando', 7),
					('Ixtapa', 7),
					('Oxchuc', 7),
					('Ostuac�n', 7),
					('Coapilla', 7),
					('Tapilula', 7),
					('Simojovel', 7),
					('Pantelh�', 7),
					('Benem�rito de las Américas', 7),
					('Bella Vista', 7),
					('Totolapa', 7),
					('Jiquipilas', 7),
					('Acacoyagua', 7),
					('Suchiate', 7),
					('Amatenango de la Frontera', 7),
					('Osumacinta', 7),
					('Teopisca', 7),
					('Juárez', 7),
					('Tecpat�n', 7),
					('Amat�n', 7),
					('Soyal�', 7),
					('Santiago el Pinar', 7),
					('Yajal�n', 7),
					('Comit�n de Dom�nguez', 7),
					('Las Margaritas', 7),
					('Montecristo de Guerrero', 7),
					('Pijijiapan', 7),
					('Huehuet�n', 7),
					('Cacahoat�n', 7),
					('Ocozocoautla de Espinosa', 7),
					('Acala', 7),
					('Tenejapa', 7),
					('Ixtacomit�n', 7),
					('Tapalapa', 7),
					('Pueblo Nuevo Solistahuac�n', 7),
					('El Bosque', 7),
					('Salto de Agua', 7),
					('Palenque', 7),
					('La Trinitaria', 7),
					('Las Rosas', 7),
					('Villaflores', 7),
					('Villa Comaltitl�n', 7),
					('Metapa', 7),
					('La Grandeza', 7),
					('Riva Palacio', 8),
					('Galeana', 8),
					('Juárez', 8),
					('Manuel Benavides', 8),
					('Guachochi', 8),
					('Moris', 8),
					('San Francisco del Oro', 8),
					('Valle de Zaragoza', 8),
					('Coronado', 8),
					('Ascensión', 8),
					('Namiquipa', 8),
					('Ojinaga', 8),
					('Satev�', 8),
					('Carich�', 8),
					('Urique', 8),
					('Santa B�rbara', 8),
					('López', 8),
					('Bach�niva', 8),
					('Gómez Far�as', 8),
					('Praxedis G. Guerrero', 8),
					('Rosales', 8),
					('Cusihuiriachi', 8),
					('Maguarichi', 8),
					('Huejotit�n', 8),
					('San Francisco de Conchos', 8),
					('Cuauhtémoc', 8),
					('Casas Grandes', 8),
					('Matach�', 8),
					('Julimes', 8),
					('Nonoava', 8),
					('Ocampo', 8),
					('Guadalupe y Calvo', 8),
					('Saucillo', 8),
					('Jiménez', 8),
					('Nuevo Casas Grandes', 8),
					('Madera', 8),
					('Coyame del Sotol', 8),
					('Dr. Belisario Dom�nguez', 8),
					('Santa Isabel', 8),
					('Batopilas', 8),
					('Balleza', 8),
					('Allende', 8),
					('Aquiles Serd�n', 8),
					('Buenaventura', 8),
					('Guadalupe', 8),
					('Delicias', 8),
					('Bocoyna', 8),
					('Ch�nipas', 8),
					('Rosario', 8),
					('La Cruz', 8),
					('Chihuahua', 8),
					('Janos', 8),
					('Tem�sachic', 8),
					('Aldama', 8),
					('San Francisco de Borja', 8),
					('Uruachi', 8),
					('Morelos', 8),
					('Camargo', 8),
					('Matamoros', 8),
					('Guerrero', 8),
					('Ignacio Zaragoza', 8),
					('Ahumada', 8),
					('Meoqui', 8),
					('Gran Morelos', 8),
					('Guazapares', 8),
					('El Tule', 8),
					('Hidalgo del Parral', 8),
					('Iztacalco', 9),
					('Xochimilco', 9),
					('Cuajimalpa de Morelos', 9),
					('Tl�huac', 9),
					('Azcapotzalco', 9),
					('La Magdalena Contreras', 9),
					('Gustavo A. Madero', 9),
					('Venustiano Carranza', 9),
					('Coyoac�n', 9),
					('Milpa Alta', 9),
					('Álvaro Obregón', 9),
					('Iztapalapa', 9),
					('Cuauhtémoc', 9),
					('Tlalpan', 9),
					('Benito Juárez', 9),
					('Miguel Hidalgo', 9),
					('Tamazula', 10),
					('Nombre de Dios', 10),
					('Tlahualilo', 10),
					('El Oro', 10),
					('San Juan del Río', 10),
					('Pe��n Blanco', 10),
					('Gómez Palacio', 10),
					('Ind�', 10),
					('Santa Clara', 10),
					('Canatl�n', 10),
					('Ot�ez', 10),
					('S�chil', 10),
					('Ocampo', 10),
					('San Luis del Cordero', 10),
					('Topia', 10),
					('Poanas', 10),
					('Mapim�', 10),
					('Tepehuanes', 10),
					('General Sim�n Bolívar', 10),
					('Coneto de Comonfort', 10),
					('Guadalupe Victoria', 10),
					('Mezquital', 10),
					('San Bernardo', 10),
					('Cuencam�', 10),
					('Durango', 10),
					('Santiago Papasquiaro', 10),
					('Vicente Guerrero', 10),
					('Hidalgo', 10),
					('Nazas', 10),
					('Canelas', 10),
					('P�nuco de Coronado', 10),
					('Lerdo', 10),
					('San Pedro del Gallo', 10),
					('San Juan de Guadalupe', 10),
					('Nuevo Ideal', 10),
					('San Dimas', 10),
					('Pueblo Nuevo', 10),
					('Guanacev�', 10),
					('Rodeo', 10),
					('Guanajuato', 11),
					('Pueblo Nuevo', 11),
					('San Miguel de Allende', 11),
					('Doctor Mora', 11),
					('Cortazar', 11),
					('Tarandacuao', 11),
					('Manuel Doblado', 11),
					('Le�n', 11),
					('Xich�', 11),
					('Comonfort', 11),
					('Coroneo', 11),
					('Uriangato', 11),
					('Romita', 11),
					('Cuer�maro', 11),
					('San Diego de la Unión', 11),
					('San José Iturbide', 11),
					('Jaral del Progreso', 11),
					('Salvatierra', 11),
					('Salamanca', 11),
					('Ocampo', 11),
					('Santa Catarina', 11),
					('Villagr�n', 11),
					('Tarimoro', 11),
					('Purísima del Rincón', 11),
					('Huan�maro', 11),
					('Victoria', 11),
					('Apaseo el Grande', 11),
					('Jer�cuaro', 11),
					('Santiago Maravat�o', 11),
					('Silao de la Victoria', 11),
					('P�njamo', 11),
					('Dolores Hidalgo Cuna de la Independencia Nacional', 11),
					('Tierra Blanca', 11),
					('Valle de Santiago', 11),
					('Morole�n', 11),
					('Irapuato', 11),
					('San Felipe', 11),
					('Atarjea', 11),
					('Santa Cruz de Juventino Rosas', 11),
					('Ac�mbaro', 11),
					('San Francisco del Rincón', 11),
					('Abasolo', 11),
					('San Luis de la Paz', 11),
					('Celaya', 11),
					('Apaseo el Alto', 11),
					('Yuriria', 11),
					('Cuautepec', 12),
					('Leonardo Bravo', 12),
					('San Marcos', 12),
					('Pilcaya', 12),
					('Cocula', 12),
					('San Miguel Totolapan', 12),
					('Coyuca de Ben�tez', 12),
					('Zitlala', 12),
					('Zapotitl�n Tablas', 12),
					('San Luis Acatl�n', 12),
					('Tlacoachistlahuaca', 12),
					('Cuajinicuilapa', 12),
					('Tecoanapa', 12),
					('Taxco de Alarc�n', 12),
					('Arcelia', 12),
					('Coyuca de Catal�n', 12),
					('T�cpan de Galeana', 12),
					('Chilapa de Álvarez', 12),
					('Tlapa de Comonfort', 12),
					('Iliatenco', 12),
					('Azoy�', 12),
					('Ayutla de los Libres', 12),
					('Huitzuco de los Figueroa', 12),
					('Ixcateopan de Cuauhtémoc', 12),
					('Cutzamala de Pinz�n', 12),
					('Petatl�n', 12),
					('Atenango del Río', 12),
					('Huamuxtitl�n', 12),
					('Atlixtac', 12),
					('Cochoapa el Grande', 12),
					('Florencio Villarreal', 12),
					('General Heliodoro Castillo', 12),
					('Juan R. Escudero', 12),
					('Tetipac', 12),
					('Cuetzala del Progreso', 12),
					('Zir�ndaro', 12),
					('Benito Juárez', 12),
					('Ahuacuotzingo', 12),
					('Xalpatl�huac', 12),
					('Atlamajalcingo del Monte', 12),
					('Ometepec', 12),
					('Marquelia', 12),
					('Quechultenango', 12),
					('Eduardo Neri', 12),
					('General Canuto A. Neri', 12),
					('Tlalchapa', 12),
					('Zihuatanejo de Azueta', 12),
					('Cual�c', 12),
					('Alpoyeca', 12),
					('Malinaltepec', 12),
					('Copala', 12),
					('Tixtla de Guerrero', 12),
					('Iguala de la Independencia', 12),
					('Teloloapan', 12),
					('Tlapehuala', 12),
					('La Unión de Isidoro Montes de Oca', 12),
					('Olinal�', 12),
					('M�rtir de Cuilapan', 12),
					('Acatepec', 12),
					('Metlat�noc', 12),
					('Xochistlahuaca', 12),
					('Igualapa', 12),
					('Chilpancingo de los Bravo', 12),
					('Acapulco de Juárez', 12),
					('Buenavista de Cu�llar', 12),
					('Apaxtla', 12),
					('Ajuchitl�n del Progreso', 12),
					('Atoyac de Álvarez', 12),
					('José Joaqu�n de Herrera', 12),
					('Tlalixtaquilla de Maldonado', 12),
					('Tlacoapa', 12),
					('Juchit�n', 12),
					('Mochitl�n', 12),
					('Tepecoacuilco de Trujano', 12),
					('Pedro Ascencio Alquisiras', 12),
					('Pungarabato', 12),
					('Coahuayutla de José María Izazaga', 12),
					('Copalillo', 12),
					('Xochihuehuetl�n', 12),
					('Copanatoyac', 12),
					('Alcozauca de Guerrero', 12),
					('Mineral del Chico', 13),
					('Pacula', 13),
					('Alfajayucan', 13),
					('El Arenal', 13),
					('Chapantongo', 13),
					('Jaltoc�n', 13),
					('Lolotla', 13),
					('Atotonilco el Grande', 13),
					('Tenango de Doria', 13),
					('Santiago Tulantepec de Lugo Guerrero', 13),
					('Almoloya', 13),
					('Zapotl�n de Juárez', 13),
					('Nicolás Flores', 13),
					('Santiago de Anaya', 13),
					('Tlahuelilpan', 13),
					('Atotonilco de Tula', 13),
					('Xochiatipan', 13),
					('Calnali', 13),
					('Huehuetla', 13),
					('Tulancingo de Bravo', 13),
					('Villa de Tezontepec', 13),
					('Ajacuba', 13),
					('Chapulhuac�n', 13),
					('Tecozautla', 13),
					('Progreso de Obregón', 13),
					('Tetepango', 13),
					('Atlapexco', 13),
					('Tlahuiltepa', 13),
					('Metztitl�n', 13),
					('Acatl�n', 13),
					('Tizayuca', 13),
					('Tepeapulco', 13),
					('Pachuca de Soto', 13),
					('Pisaflores', 13),
					('Tasquillo', 13),
					('Francisco I. Madero', 13),
					('Tepeji del Río de Ocampo', 13),
					('San Felipe Orizatl�n', 13),
					('Tepehuac�n de Guerrero', 13),
					('Tianguistengo', 13),
					('Agua Blanca de Iturbide', 13),
					('Cuautepec de Hinojosa', 13),
					('Tlanalapa', 13),
					('Mineral de la Reforma', 13),
					('Zimap�n', 13),
					('Actopan', 13),
					('Tezontepec de Aldama', 13),
					('Atitalaquia', 13),
					('Yahualica', 13),
					('Zacualtip�n de Ángeles', 13),
					('Metepec', 13),
					('Epazoyucan', 13),
					('Tolcayuca', 13),
					('Mineral del Monte', 13),
					('La Misión', 13),
					('Huichapan', 13),
					('Mixquiahuala de Juárez', 13),
					('Tepetitl�n', 13),
					('Huautla', 13),
					('Tlanchinol', 13),
					('Eloxochitl�n', 13),
					('Huasca de Ocampo', 13),
					('Singuilucan', 13),
					('Emiliano Zapata', 13),
					('Jacala de Ledezma', 13),
					('Cardonal', 13),
					('San Salvador', 13),
					('Tula de Allende', 13),
					('Huejutla de Reyes', 13),
					('Molango de Escamilla', 13),
					('Xochicoatl�n', 13),
					('San Bartolo Tutotepec', 13),
					('Acaxochitl�n', 13),
					('Apan', 13),
					('San Agustín Tlaxiaca', 13),
					('Ixmiquilpan', 13),
					('Nopala de Villagr�n', 13),
					('Chilcuautla', 13),
					('Tlaxcoapan', 13),
					('Huazalingo', 13),
					('Juárez Hidalgo', 13),
					('San Agustín Metzquititl�n', 13),
					('Omitl�n de Juárez', 13),
					('Zempoala', 13),
					('El Arenal', 14),
					('El Salto', 14),
					('Chapala', 14),
					('Colotl�n', 14),
					('Etzatl�n', 14),
					('Mixtl�n', 14),
					('San Ignacio Cerro Gordo', 14),
					('Lagos de Moreno', 14),
					('Jamay', 14),
					('Cuautla', 14),
					('Tenamaxtl�n', 14),
					('Villa Purificaci�n', 14),
					('Concepción de Buenos Aires', 14),
					('Tuxcueca', 14),
					('ToLimón', 14),
					('San Cristóbal de la Barranca', 14),
					('Cuqu�o', 14),
					('Jocotepec', 14),
					('Villa Guerrero', 14),
					('Tequila', 14),
					('Teuchitl�n', 14),
					('San Miguel el Alto', 14),
					('Mexticac�n', 14),
					('Tototl�n', 14),
					('Unión de Tula', 14),
					('Tomatl�n', 14),
					('El Grullo', 14),
					('Cihuatl�n', 14),
					('Tapalpa', 14),
					('Zapotiltic', 14),
					('Tecalitl�n', 14),
					('Tonalá', 14),
					('Villa Corona', 14),
					('Zapotl�n del Rey', 14),
					('Huej�car', 14),
					('San Juanito de Escobedo', 14),
					('San Sebasti�n del Oeste', 14),
					('Villa Hidalgo', 14),
					('Unión de San Antonio', 14),
					('Ayotl�n', 14),
					('Talpa de Allende', 14),
					('Chiquilistl�n', 14),
					('Autl�n de Navarro', 14),
					('Techaluta de Montenegro', 14),
					('Mazamitla', 14),
					('Tuxpan', 14),
					('Tala', 14),
					('Tlajomulco de Z��iga', 14),
					('Juanacatl�n', 14),
					('Totatiche', 14),
					('Magdalena', 14),
					('Guachinango', 14),
					('Arandas', 14),
					('Valle de Guadalupe', 14),
					('Ocotl�n', 14),
					('Atenguillo', 14),
					('Tecolotl�n', 14),
					('Tuxcacuesco', 14),
					('Gómez Far�as', 14),
					('Tizap�n el Alto', 14),
					('San Gabriel', 14),
					('Santa María del Oro', 14),
					('Zapopan', 14),
					('Acatic', 14),
					('Atemajac de Brizuela', 14),
					('Mezquitic', 14),
					('San Mart�n de Bola�os', 14),
					('Ahualulco de Mercado', 14),
					('Jalostotitl�n', 14),
					('Yahualica de González Gallo', 14),
					('Tepatitl�n de Morelos', 14),
					('Degollado', 14),
					('Cabo Corrientes', 14),
					('El Limón', 14),
					('Cuautitl�n de Garc�a Barrag�n', 14),
					('Sayula', 14),
					('Quitupan', 14),
					('Pihuamo', 14),
					('Amatit�n', 14),
					('Acatl�n de Juárez', 14),
					('Poncitl�n', 14),
					('Santa María de los Ángeles', 14),
					('San Marcos', 14),
					('Mascota', 14),
					('Teocaltiche', 14),
					('Ojuelos de Jalisco', 14),
					('La Barca', 14),
					('Atengo', 14),
					('Juchitl�n', 14),
					('La Huerta', 14),
					('Atoyac', 14),
					('La Manzanilla de la Paz', 14),
					('Zapotitl�n de Vadillo', 14),
					('Ixtlahuac�n del Río', 14),
					('San Pedro Tlaquepaque', 14),
					('Ixtlahuac�n de los Membrillos', 14),
					('Bola�os', 14),
					('Hostotipaquillo', 14),
					('San Mart�n Hidalgo', 14),
					('San Julián', 14),
					('Cañadas de Obregón', 14),
					('Atotonilco el Alto', 14),
					('Ayutla', 14),
					('Cocula', 14),
					('Tonaya', 14),
					('Zapotl�n el Grande', 14),
					('Amacueca', 14),
					('Tamazula de Gordiano', 14),
					('Jilotl�n de los Dolores', 14),
					('Guadalajara', 14),
					('Zapotlanejo', 14),
					('Zacoalco de Torres', 14),
					('Huejuquilla el Alto', 14),
					('Chimaltit�n', 14),
					('Ameca', 14),
					('San Juan de los Lagos', 14),
					('Encarnaci�n de D�az', 14),
					('San Diego de Alejandr�a', 14),
					('Jesús María', 14),
					('Puerto Vallarta', 14),
					('Ejutla', 14),
					('Casimiro Castillo', 14),
					('Teocuitatl�n de Corona', 14),
					('Valle de Juárez', 14),
					('Tonila', 14),
					('Toluca', 15),
					('San Felipe del Progreso', 15),
					('Villa de Allende', 15),
					('Temascaltepec', 15),
					('Texcaltitl�n', 15),
					('Lerma', 15),
					('San Antonio la Isla', 15),
					('Almoloya del Río', 15),
					('Naucalpan de Juárez', 15),
					('Isidro Fabela', 15),
					('Melchor Ocampo', 15),
					('Coacalco de Berrioz�bal', 15),
					('Otumba', 15),
					('Texcoco', 15),
					('Valle de Chalco Solidaridad', 15),
					('Tepetlixpa', 15),
					('Timilpan', 15),
					('Temoaya', 15),
					('Zacazonapan', 15),
					('Amatepec', 15),
					('Ixtapan de la Sal', 15),
					('Mexicaltzingo', 15),
					('Malinalco', 15),
					('Ocoyoacac', 15),
					('Villa del Carb�n', 15),
					('Cuautitl�n Izcalli', 15),
					('Tequixquiac', 15),
					('Teotihuac�n', 15),
					('Chiautla', 15),
					('La Paz', 15),
					('Tenango del Aire', 15),
					('Aculco', 15),
					('Jocotitl�n', 15),
					('Ixtapan del Oro', 15),
					('Tejupilco', 15),
					('Villa Guerrero', 15),
					('Otzolotepec', 15),
					('Ray�n', 15),
					('Tianguistenco', 15),
					('Polotitl�n', 15),
					('Tepotzotl�n', 15),
					('Tultepec', 15),
					('Jaltenco', 15),
					('Nopaltepec', 15),
					('Atenco', 15),
					('Cocotitl�n', 15),
					('Atlautla', 15),
					('El Oro', 15),
					('Villa Victoria', 15),
					('Amanalco', 15),
					('Sultepec', 15),
					('Zumpahuac�n', 15),
					('Chapultepec', 15),
					('Atizap�n', 15),
					('Atizap�n de Zaragoza', 15),
					('Nicolás Romero', 15),
					('Cuautitl�n', 15),
					('Hueypoxtla', 15),
					('Acolman', 15),
					('Tepetlaoxtoc', 15),
					('Chalco', 15),
					('Juchitepec', 15),
					('Atlacomulco', 15),
					('Jiquipilco', 15),
					('Otzoloapan', 15),
					('San Sim�n de Guerrero', 15),
					('Almoloya de Alquisiras', 15),
					('Metepec', 15),
					('Tenancingo', 15),
					('Capulhuac', 15),
					('Soyaniquilpan de Juárez', 15),
					('Huehuetoca', 15),
					('Zumpango', 15),
					('Nextlalpan', 15),
					('Tezoyuca', 15),
					('Chicoloapan', 15),
					('Ayapango', 15),
					('Nezahualc�yotl', 15),
					('Acambay de Ru�z Casta�eda', 15),
					('San José del Rincón', 15),
					('Donato Guerra', 15),
					('Zinacantepec', 15),
					('Coatepec Harinas', 15),
					('Xonacatl�n', 15),
					('Tenango del Valle', 15),
					('Texcalyacac', 15),
					('Tlalnepantla de Baz', 15),
					('Jilotzingo', 15),
					('Tultitl�n', 15),
					('Tec�mac', 15),
					('Axapusco', 15),
					('Chiconcuac', 15),
					('Temamatla', 15),
					('Amecameca', 15),
					('Morelos', 15),
					('Almoloya de Juárez', 15),
					('Valle de Bravo', 15),
					('Tlatlaya', 15),
					('Tonatico', 15),
					('Calimaya', 15),
					('Ocuilan', 15),
					('Huixquilucan', 15),
					('Chapa de Mota', 15),
					('Teoloyucan', 15),
					('Apaxco', 15),
					('San Mart�n de las Pir�mides', 15),
					('Papalotla', 15),
					('Ixtapaluca', 15),
					('Ozumba', 15),
					('Temascalcingo', 15),
					('Ixtlahuaca', 15),
					('Santo Tom�s', 15),
					('Luvianos', 15),
					('Zacualpan', 15),
					('San Mateo Atenco', 15),
					('Joquicingo', 15),
					('Xalatlaco', 15),
					('Jilotepec', 15),
					('Coyotepec', 15),
					('Ecatepec de Morelos', 15),
					('Tonanitla', 15),
					('Temascalapa', 15),
					('Chimalhuac�n', 15),
					('Tlalmanalco', 15),
					('Ecatzingo', 15),
					('Apatzing�n', 16),
					('Lázaro Cárdenas', 16),
					('Charo', 16),
					('Zit�cuaro', 16),
					('Turicato', 16),
					('La Huacana', 16),
					('Quiroga', 16),
					('Panind�cuaro', 16),
					('Chuc�ndiro', 16),
					('Sahuayo', 16),
					('Ixtl�n', 16),
					('Villamar', 16),
					('Cotija', 16),
					('Tingambato', 16),
					('Buenavista', 16),
					('Aquila', 16),
					('Maravat�o', 16),
					('Tuxpan', 16),
					('Erongar�cuaro', 16),
					('M�gica', 16),
					('San Lucas', 16),
					('Morelia', 16),
					('Puru�ndiro', 16),
					('Morelos', 16),
					('Zinap�cuaro', 16),
					('Vista Hermosa', 16),
					('Penjamillo', 16),
					('Chilchota', 16),
					('Paracho', 16),
					('Coahuayana', 16),
					('Contepec', 16),
					('Tiquicheo de Nicolás Romero', 16),
					('Juárez', 16),
					('Taretan', 16),
					('Nocup�taro', 16),
					('Lagunillas', 16),
					('Tlazazalca', 16),
					('Tar�mbaro', 16),
					('Cojumatl�n de R�gules', 16),
					('Numar�n', 16),
					('Zamora', 16),
					('Ting�ind�n', 16),
					('Perib�n', 16),
					('Aguililla', 16),
					('Arteaga', 16),
					('Senguio', 16),
					('Jungapeo', 16),
					('Tac�mbaro', 16),
					('Ario', 16),
					('Coeneo', 16),
					('Angamacutiro', 16),
					('Cuitzeo', 16),
					('Quer�ndaro', 16),
					('Yur�cuaro', 16),
					('Jiquilpan', 16),
					('Tangamandapio', 16),
					('Nahuatzen', 16),
					('Coalcom�n de Vázquez Pallares', 16),
					('Hidalgo', 16),
					('Angangueo', 16),
					('P�tzcuaro', 16),
					('Nuevo Urecho', 16),
					('Huetamo', 16),
					('Madero', 16),
					('Jiménez', 16),
					('Álvaro Obregón', 16),
					('Pajacuar�n', 16),
					('Zin�paro', 16),
					('Tanganc�cuaro', 16),
					('Charapan', 16),
					('Nuevo Parangaricutiro', 16),
					('Par�cuaro', 16),
					('Epitacio Huerta', 16),
					('Tzitzio', 16),
					('Tuzantla', 16),
					('Ziracuaretiro', 16),
					('Churumuco', 16),
					('Tzintzuntzan', 16),
					('Zacapu', 16),
					('Cop�ndaro', 16),
					('Brise�as', 16),
					('La Piedad', 16),
					('Chavinda', 16),
					('Tocumbo', 16),
					('Los Reyes', 16),
					('Tepalcatepec', 16),
					('Tumbiscat�o', 16),
					('Irimbo', 16),
					('Ocampo', 16),
					('Huiramba', 16),
					('Salvador Escalante', 16),
					('Huaniqueo', 16),
					('José Sixto Verduzco', 16),
					('Huandacareo', 16),
					('Indaparapeo', 16),
					('Tanhuato', 16),
					('Marcos Castellanos', 16),
					('Jacona', 16),
					('Cher�n', 16),
					('Chinicuila', 16),
					('Tlalpujahua', 16),
					('Aporo', 16),
					('Susupuato', 16),
					('Gabriel Zamora', 16),
					('Car�cuaro', 16),
					('Acuitzio', 16),
					('Pur�pero', 16),
					('Santa Ana Maya', 16),
					('Venustiano Carranza', 16),
					('Churintzio', 16),
					('Ecuandureo', 16),
					('Uruapan', 16),
					('Tanc�taro', 16),
					('Tepoztl�n', 17),
					('Mazatepec', 17),
					('Zacatepec', 17),
					('Zacualpan', 17),
					('Miacatl�n', 17),
					('Cuautla', 17),
					('Atlatlahucan', 17),
					('Jantetelco', 17),
					('Tlayacapan', 17),
					('Puente de Ixtla', 17),
					('Tetela del Volc�n', 17),
					('Tepalcingo', 17),
					('Huitzilac', 17),
					('Tetecala', 17),
					('Tlaltizap�n de Zapata', 17),
					('Temoac', 17),
					('Temixco', 17),
					('Yautepec', 17),
					('Totolapan', 17),
					('Axochiapan', 17),
					('Tlalnepantla', 17),
					('Amacuzac', 17),
					('Xochitepec', 17),
					('Jojutla', 17),
					('Cuernavaca', 17),
					('Coatl�n del Río', 17),
					('Emiliano Zapata', 17),
					('Ocuituco', 17),
					('Tlaquiltenango', 17),
					('Jiutepec', 17),
					('Ayala', 17),
					('Yecapixtla', 17),
					('Jonacatepec', 17),
					('Tuxpan', 18),
					('Rosamorada', 18),
					('Ahuacatl�n', 18),
					('Del Nayar', 18),
					('San Pedro Lagunillas', 18),
					('Acaponeta', 18),
					('Bah�a de Banderas', 18),
					('Amatl�n de Ca�as', 18),
					('Tepic', 18),
					('Ru�z', 18),
					('Jala', 18),
					('Huajicori', 18),
					('Xalisco', 18),
					('Santiago Ixcuintla', 18),
					('Compostela', 18),
					('Ixtl�n del Río', 18),
					('La Yesca', 18),
					('Santa María del Oro', 18),
					('Tecuala', 18),
					('San Blas', 18),
					('Sabinas Hidalgo', 19),
					('Higueras', 19),
					('Santa Catarina', 19),
					('Los Ramones', 19),
					('Santiago', 19),
					('Galeana', 19),
					('Lampazos de Naranjo', 19),
					('Ciénega de Flores', 19),
					('Melchor Ocampo', 19),
					('Pesquer�a', 19),
					('China', 19),
					('Rayones', 19),
					('Mier y Noriega', 19),
					('Vallecillo', 19),
					('Agualeguas', 19),
					('San Nicolás de los Garza', 19),
					('Los Aldamas', 19),
					('General Terán', 19),
					('Doctor Arroyo', 19),
					('Bustamante', 19),
					('Abasolo', 19),
					('General Escobedo', 19),
					('Doctor González', 19),
					('Juárez', 19),
					('Iturbide', 19),
					('Anáhuac', 19),
					('Salinas Victoria', 19),
					('Cerralvo', 19),
					('Apodaca', 19),
					('General Bravo', 19),
					('Montemorelos', 19),
					('General Zaragoza', 19),
					('Villaldama', 19),
					('General Zuazua', 19),
					('San Pedro Garza Garc�a', 19),
					('Los Herreras', 19),
					('Allende', 19),
					('Hualahuises', 19),
					('Mina', 19),
					('Hidalgo', 19),
					('Garc�a', 19),
					('Mar�n', 19),
					('Guadalupe', 19),
					('Linares', 19),
					('Monterrey', 19),
					('Par�s', 19),
					('General Trevi�o', 19),
					('El Carmen', 19),
					('Doctor Coss', 19),
					('Cadereyta Jiménez', 19),
					('Aramberri', 19),
					('Santa Catarina Tayata', 20),
					('Santo Tom�s Ocotepec', 20),
					('Magdalena Yodocono de Porfirio D�az', 20),
					('San Andrés Nuxi�o', 20),
					('Ciudad Ixtepec', 20),
					('Unión Hidalgo', 20),
					('Santo Domingo Tepuxtepec', 20),
					('Tamazul�pam del Esp�ritu Santo', 20),
					('Matías Romero Avenda�o', 20),
					('Villa D�az Ordaz', 20),
					('Santo Domingo Albarradas', 20),
					('San Juan del Río', 20),
					('San Juan Juquila Mixes', 20),
					('Santa María Quiegolani', 20),
					('Guevea de Humboldt', 20),
					('San Pedro Huamelula', 20),
					('San Sim�n Almolongas', 20),
					('San Ildefonso Amatl�n', 20),
					('San Sebasti�n Coatl�n', 20),
					('San Miguel Suchixtepec', 20),
					('San Juan Bautista Atatlahuca', 20),
					('Santa Catarina Loxicha', 20),
					('Santiago Suchilquitongo', 20),
					('San Pedro el Alto', 20),
					('Guadalupe Etla', 20),
					('San Pedro Amuzgos', 20),
					('San Andrés Huay�pam', 20),
					('Santa Catarina Yosonot�', 20),
					('Acatl�n de P�rez Figueroa', 20),
					('Santiago Yosond�a', 20),
					('San Juan Bautista Valle Nacional', 20),
					('Santa Cruz Amilpas', 20),
					('Santa Cruz Acatepec', 20),
					('San Jacinto Tlacotepec', 20),
					('Huautepec', 20),
					('Villa de Zaachila', 20),
					('San Juan de los Cu�s', 20),
					('Santa Catarina Quian�', 20),
					('San Miguel Santa Flor', 20),
					('Santa María Zaniza', 20),
					('San Juan Tepeuxila', 20),
					('San Francisco Sola', 20),
					('San Juan Quiotepec', 20),
					('Santa Ana Zegache', 20),
					('San Miguel Alo�pam', 20),
					('Santa Catarina Minas', 20),
					('Nuevo Zoqui�pam', 20),
					('San Pedro Taviche', 20),
					('Santiago Laxopa', 20),
					('Taniche', 20),
					('San Juan Juquila Vijanos', 20),
					('San Sebasti�n Ixcapa', 20),
					('San Andrés Ya�', 20),
					('Santiago Jamiltepec', 20),
					('Santo Domingo Xagac�a', 20),
					('San Andrés Huaxpaltepec', 20),
					('Heroica Ciudad de Huajuapan de Le�n', 20),
					('Santa Catarina Juquila', 20),
					('Zapotitl�n Palmas', 20),
					('Zapotitl�n Lagunas', 20),
					('Tezoatl�n de Segura y Luna', 20),
					('San Sim�n Zahuatl�n', 20),
					('Concepción Buenavista', 20),
					('Santiago Tepetlapa', 20),
					('Santa Cruz de Bravo', 20),
					('Teotongo', 20),
					('San Juan Teposcolula', 20),
					('Santiago Nejapilla', 20),
					('Santiago Huauclilla', 20),
					('Santa In�s de Zaragoza', 20),
					('Heroica Ciudad de Tlaxiaco', 20),
					('San Bartolom� Yucua�e', 20),
					('Santa María Yosoy�a', 20),
					('San Francisco Jaltepetongo', 20),
					('San Miguel Piedras', 20),
					('San Dionisio del Mar', 20),
					('San Pedro Tapanatepec', 20),
					('Santa María Tlahuitoltepec', 20),
					('San Pedro Ocotepec', 20),
					('El Barrio de la Soledad', 20),
					('Santa Ana del Valle', 20),
					('San Jerónimo Tlacochahuaya', 20),
					('Santa María Zoquitl�n', 20),
					('Santa María Ecatepec', 20),
					('Santa María Jalapa del Marqu�s', 20),
					('San Pedro Comitancillo', 20),
					('San Miguel Tenango', 20),
					('Santa Ana', 20),
					('San Pedro Mixtepec -Dto. 26 -', 20),
					('Santa María Ozolotepec', 20),
					('San Juan Ozolotepec', 20),
					('San Pablo Huitzo', 20),
					('Santa María Tonameca', 20),
					('San Agustín Etla', 20),
					('Constancia del Rosario', 20),
					('Santiago Tlazoyaltepec', 20),
					('San Esteban Atatlahuca', 20),
					('Loma Bonita', 20),
					('Santa Luc�a Monteverde', 20),
					('San Felipe Jalapa de D�az', 20),
					('San Miguel Mixtepec', 20),
					('San Lorenzo Cuaunecuiltitla', 20),
					('San Agustín de las Juntas', 20),
					('San Mart�n Toxpalan', 20),
					('Santa In�s Yatzeche', 20),
					('San Mateo Yoloxochitl�n', 20),
					('Santa Gertrudis', 20),
					('Santa Ana Cuauhtémoc', 20),
					('San Mateo Yucutindoo', 20),
					('Santos Reyes P�palo', 20),
					('San Vicente Lachix�o', 20),
					('San Pedro Jaltepetongo', 20),
					('Santo Tom�s Jalieza', 20),
					('Ixtl�n de Juárez', 20),
					('San Dionisio Ocotl�n', 20),
					('San Miguel del Río', 20),
					('San Andrés Zabache', 20),
					('Santa Catarina Lachatao', 20),
					('Coatecas Altas', 20),
					('San Juan Yatzona', 20),
					('San Juan Cacahuatepec', 20),
					('San Andrés Solaga', 20),
					('Santiago Tapextla', 20),
					('San Francisco Cajonos', 20),
					('Pinotepa de Don Luis', 20),
					('Santiago Yaveo', 20),
					('Tataltepec de Vald�s', 20),
					('Santa Catarina Zapoquila', 20),
					('Santos Reyes Nopala', 20),
					('Santiago Huajolotitl�n', 20),
					('San Miguel Ahuehuetitl�n', 20),
					('San Miguel Amatitl�n', 20),
					('Santo Domingo Yodohino', 20),
					('San Mateo Tlapiltepec', 20),
					('San Lorenzo Victoria', 20),
					('La Trinidad Vista Hermosa', 20),
					('San Antonino Monte Verde', 20),
					('Santa María Nduayaco', 20),
					('Santiago Apoala', 20),
					('Santiago Tillo', 20),
					('San Juan Mixtepec -Dto. 08 -', 20),
					('Santiago Nundiche', 20),
					('San Miguel Achiutla', 20),
					('San Mateo Pe�asco', 20),
					('Magdalena Zahuatl�n', 20),
					('Santo Domingo Nuxa�', 20),
					('Santo Domingo Ingenio', 20),
					('Santo Domingo Zanatepec', 20),
					('San Juan Mazatl�n', 20),
					('Santa María Tepantlali', 20),
					('Santo Domingo Petapa', 20),
					('Teotitl�n del Valle', 20),
					('San Juan Teitipac', 20),
					('San Lorenzo Albarradas', 20),
					('Santa Ana Tavela', 20),
					('Santa Catalina Quier�', 20),
					('Santa María Guienagati', 20),
					('San Mateo del Mar', 20),
					('San José Lachiguiri', 20),
					('San José del Pe�asco', 20),
					('San Mateo Río Hondo', 20),
					('San Francisco Ozolotepec', 20),
					('San Juan Bautista Jayacatl�n', 20),
					('San Baltazar Loxicha', 20),
					('Reyes Etla', 20),
					('Santa María Huatulco', 20),
					('San Felipe Tejal�pam', 20),
					('Santa María Ipalapa', 20),
					('Santo Domingo Tomaltepec', 20),
					('Santo Domingo Ixcatl�n', 20),
					('Ayotzintepec', 20),
					('Zimatl�n de Álvarez', 20),
					('Huautla de Jiménez', 20),
					('Santa Luc�a del Camino', 20),
					('Santiago Texcalcingo', 20),
					('Trinidad Zaachila', 20),
					('San Lucas Zoqui�pam', 20),
					('San Miguel Peras', 20),
					('Santa María Ixcatl�n', 20),
					('Santa Ana Tlapacoyan', 20),
					('San Andrés Teotil�lpam', 20),
					('Cuil�pam de Guerrero', 20),
					('Valerio Trujano', 20),
					('Santiago Minas', 20),
					('Santiago Comaltepec', 20),
					('San Antonino Castillo Velasco', 20),
					('Santa Ana Yareni', 20),
					('San Pedro Ap�stol', 20),
					('Guelatao de Juárez', 20),
					('San Mart�n Lachil�', 20),
					('Santiago Camotl�n', 20),
					('Yogana', 20),
					('Santa María Temaxcalapa', 20),
					('Santa María Cortijo', 20),
					('San Baltazar Yatzachi el Bajo', 20),
					('San Juan Colorado', 20),
					('Santiago Cho�pam', 20),
					('Santiago Tetepec', 20),
					('Cosoltepec', 20),
					('Santiago Yaitepec', 20),
					('Santiago Cacaloxtepec', 20),
					('San Nicolás Hidalgo', 20),
					('Santiago Ayuquililla', 20),
					('San Jorge Nuchita', 20),
					('Tlacotepec Plumas', 20),
					('Santa María Nativitas', 20),
					('San Francisco Tlapancingo', 20),
					('Villa Tej�pam de la Unión', 20),
					('Santiago Yolom�catl', 20),
					('San Miguel Huautla', 20),
					('San Andrés Sinaxtla', 20),
					('San Miguel Tlacotepec', 20),
					('San Pedro M�rtir Yucuxaco', 20),
					('San Juan Achiutla', 20),
					('San Agustín Tlacotepec', 20),
					('Magdalena Jaltepec', 20),
					('San Juan Diuxi', 20),
					('Heroica Ciudad de Juchit�n de Zaragoza', 20),
					('San Francisco del Mar', 20),
					('Santiago Zacatepec', 20),
					('Santiago Atitl�n', 20),
					('Santiago Ixcuintepec', 20),
					('San Sebasti�n Abasolo', 20),
					('Santiago Matatl�n', 20),
					('San Lucas Quiavin�', 20),
					('San Carlos Yautepec', 20),
					('San Pedro M�rtir Quiechapa', 20),
					('Santiago Laollaga', 20),
					('Santo Domingo Tehuantepec', 20),
					('San Nicolás', 20),
					('Monjas', 20),
					('San Jerónimo Coatl�n', 20),
					('San Sebasti�n Río Hondo', 20),
					('Villa de Etla', 20),
					('Santo Domingo de Morelos', 20),
					('Magdalena Apasco', 20),
					('Pluma Hidalgo', 20),
					('Santo Tom�s Mazaltepec', 20),
					('Santa María Zacatepec', 20),
					('San Jacinto Amilpas', 20),
					('Santiago Nuyo�', 20),
					('Cosolapa', 20),
					('Santa María Yolotepec', 20),
					('San Lucas Ojitl�n', 20),
					('San Andrés Ixtlahuaca', 20),
					('San Pedro Ocopetatillo', 20),
					('�nimas Trujano', 20),
					('Santa María la Asunción', 20),
					('San Antonio Huitepec', 20),
					('Mazatl�n Villa de Flores', 20),
					('Magdalena Mixtepec', 20),
					('San Pedro Teutila', 20),
					('Santiago Amoltepec', 20),
					('Santa María P�palo', 20),
					('Santa María Sola', 20),
					('Natividad', 20),
					('Ocotl�n de Morelos', 20),
					('San Pedro Yaneri', 20),
					('San Miguel Tilqui�pam', 20),
					('Capul�lpam de Méndez', 20),
					('Yaxe', 20),
					('Santa María Yaves�a', 20),
					('San Agustín Amatengo', 20),
					('Tanetze de Zaragoza', 20),
					('Mártires de Tacubaya', 20),
					('San Melchor Betaza', 20),
					('Santo Domingo Armenta', 20),
					('San Pedro Cajonos', 20),
					('San Agustín Chayuco', 20),
					('San Juan Comaltepec', 20),
					('San Miguel Panixtlahuaca', 20),
					('San Jerónimo Silacayoapilla', 20),
					('San Pedro Mixtepec -Dto. 22 -', 20),
					('San Juan Cieneguilla', 20),
					('San Juan Bautista Tlachichilco', 20),
					('Santa Cruz Tacache de Mina', 20),
					('Tepelmeme Villa de Morelos', 20),
					('San Miguel Tulancingo', 20),
					('Calihual�', 20),
					('San Pedro Nopala', 20),
					('San Pedro Yucunama', 20),
					('San Pedro Topiltepec', 20),
					('San Pedro Coxcaltepec Cántaros', 20),
					('San Mateo Etlatongo', 20),
					('Coicoy�n de las Flores', 20),
					('Magdalena Pe�asco', 20),
					('San Pedro Molinos', 20),
					('San Pedro Tida�', 20),
					('San Pedro Teozacoalco', 20),
					('Santiago Niltepec', 20),
					('San Francisco Ixhuat�n', 20),
					('Mixistl�n de la Reforma', 20),
					('Asunción Cacalotepec', 20),
					('Santa María Petapa', 20),
					('San Sebasti�n Teitipac', 20),
					('Magdalena Teitipac', 20),
					('San Pedro Quiatoni', 20),
					('San Bartolo Yautepec', 20),
					('Santiago Lachiguiri', 20),
					('Magdalena Tlacotepec', 20),
					('Santiago Astata', 20),
					('San Francisco Logueche', 20),
					('San Juan Mixtepec -Dto. 26 -', 20),
					('San Andrés Paxtl�n', 20),
					('San Marcial Ozolotepec', 20),
					('Santiago Tenango', 20),
					('San Bartolom� Loxicha', 20),
					('San Andrés Zautla', 20),
					('Putla Villa de Guerrero', 20),
					('Santa María Pe�oles', 20),
					('Santa María Yucuhiti', 20),
					('San Juan Bautista Tuxtepec', 20),
					('Santa Cruz Tacahua', 20),
					('San José Chiltepec', 20),
					('Santa Cruz Mixtepec', 20),
					('Santa Ana Ateixtlahuaca', 20),
					('San Antonio de la Cal', 20),
					('Santa María Teopoxco', 20),
					('San Bartolo Coyotepec', 20),
					('San José Tenango', 20),
					('Santa In�s del Monte', 20),
					('Cuyamecalco Villa de Zaragoza', 20),
					('San Francisco Cahuacu�', 20),
					('Concepción P�palo', 20),
					('Santa María Lachix�o', 20),
					('Santa María Texcatitl�n', 20),
					('San Mart�n Tilcajete', 20),
					('San Pablo Macuiltianguis', 20),
					('San Pedro M�rtir', 20),
					('Santa María Jaltianguis', 20),
					('San Jerónimo Taviche', 20),
					('San Miguel Yotao', 20),
					('La Compa��a', 20),
					('Santiago Lalopa', 20),
					('Santiago Pinotepa Nacional', 20),
					('Santa María Yalina', 20),
					('San Miguel Tlacamama', 20),
					('Villa Hidalgo', 20),
					('San Pedro Jicay�n', 20),
					('San Juan Lalana', 20),
					('Villa de Tututepec de Melchor Ocampo', 20),
					('San Juan Bautista Suchitepec', 20),
					('Santa María Temaxcaltepec', 20),
					('Santa María Camotl�n', 20),
					('San Andrés Tepetlapa', 20),
					('San Mart�n Zacatepec', 20),
					('Santo Domingo Tonalá', 20),
					('Santa Magdalena Jicotl�n', 20),
					('Santiago Yucuyachi', 20),
					('San Pedro y San Pablo Teposcolula', 20),
					('Villa de Chilapa de D�az', 20),
					('Santo Domingo Tlatay�pam', 20),
					('Santa María Apazco', 20),
					('San Juan Sayultepec', 20),
					('Santos Reyes Tepejillo', 20),
					('Santa Cruz Tayata', 20),
					('San Cristóbal Amoltepec', 20),
					('San Antonio Sinicahua', 20),
					('San Miguel Tecomatl�n', 20),
					('San Juan Tamazola', 20),
					('El Espinal', 20),
					('San Miguel Chimalapa', 20),
					('San Juan Cotzoc�n', 20),
					('San Pedro y San Pablo Ayutla', 20),
					('San Juan Guichicovi', 20),
					('Santa María Guelac�', 20),
					('Rojas de Cuauhtémoc', 20),
					('San Bartolom� Quialana', 20),
					('Nejapa de Madero', 20),
					('Santa Catarina Quioquitani', 20),
					('Santo Domingo Chihuit�n', 20),
					('San Pedro Huilotepec', 20),
					('San Luis Amatl�n', 20),
					('Santa Catarina Cuixtla', 20),
					('San Pablo Coatl�n', 20),
					('Santo Domingo Ozolotepec', 20),
					('San Jerónimo Sosola', 20),
					('San Agustín Loxicha', 20),
					('San Juan Bautista Guelache', 20),
					('San Mateo Piñas', 20),
					('San Pablo Etla', 20),
					('La Reforma', 20),
					('San Agustín Yatareni', 20),
					('San Miguel el Grande', 20),
					('San Miguel Soyaltepec', 20),
					('Santa Cruz Itundujia', 20),
					('San Felipe Usila', 20),
					('Santa Cruz Xoxocotl�n', 20),
					('Eloxochitl�n de Flores Mag�n', 20),
					('San Raymundo Jalpan', 20),
					('San Juan Coatz�spam', 20),
					('San Sebasti�n Tutla', 20),
					('Santa María Tecomavaca', 20),
					('Ayoquezco de Aldama', 20),
					('Santa María Tlalixtac', 20),
					('Santo Domingo Teojomulco', 20),
					('San Pedro Sochi�pam', 20),
					('San Ildefonso Sola', 20),
					('San Pedro Y�lox', 20),
					('Santiago Ap�stol', 20),
					('Teococuilco de Marcos P�rez', 20),
					('San Baltazar Chichic�pam', 20),
					('Santiago Xiacu�', 20),
					('San Mart�n de los Cansecos', 20),
					('San Ildefonso Villa Alta', 20),
					('San Miguel Ejutla', 20),
					('San Cristóbal Lachirioag', 20),
					('San Antonio Tepetlapa', 20),
					('San Bartolom� Zoogocho', 20),
					('San Pedro Atoyac', 20),
					('San Pablo Yaganiza', 20),
					('Santa Catarina Mechoac�n', 20),
					('Santiago Chazumba', 20),
					('San Pedro Juchatengo', 20),
					('San Andrés Dinicuiti', 20),
					('San Juan Ihualtepec', 20),
					('Fresnillo de Trujano', 20),
					('San Marcos Arteaga', 20),
					('Santiago Ihuitl�n Plumas', 20),
					('San Cristóbal Suchixtlahuaca', 20),
					('Ixpantepec Nieves', 20),
					('San Antonio Acutla', 20),
					('San Bartolo Soyaltepec', 20),
					('Asunción Nochixtl�n', 20),
					('Santo Domingo Yanhuitl�n', 20),
					('Santiago Juxtlahuaca', 20),
					('San Juan �um�', 20),
					('Santa Cruz Nundaco', 20),
					('San Juan Teita', 20),
					('Santiago Tilantongo', 20),
					('San Mateo Sindihui', 20),
					('Asunción Ixtaltepec', 20),
					('Chahuites', 20),
					('Santa María Alotepec', 20),
					('San Lucas Camotl�n', 20),
					('Tlacolula de Matamoros', 20),
					('San Pablo Villa de Mitla', 20),
					('San Juan Guelav�a', 20),
					('San Dionisio Ocotepec', 20),
					('Asunción Tlacolulita', 20),
					('Santa María Totolapilla', 20),
					('Santa María Mixtequilla', 20),
					('Miahuatl�n de Porfirio D�az', 20),
					('Santa Cruz Xitla', 20),
					('Santa Luc�a Miahuatl�n', 20),
					('San Miguel Coatl�n', 20),
					('Oaxaca de Juárez', 20),
					('San Pedro Pochutla', 20),
					('San Juan del Estado', 20),
					('Candelaria Loxicha', 20),
					('Soledad Etla', 20),
					('Mesones Hidalgo', 20),
					('Tlalixtac de Cabrera', 20),
					('Santa Catarina Ticu�', 20),
					('San José Independencia', 20),
					('San Andrés Cabecera Nueva', 20),
					('Santa María Jacatepec', 20),
					('Santa María Atzompa', 20),
					('San Francisco Huehuetl�n', 20),
					('San Pablo Huixtepec', 20),
					('San Jerónimo Tec�atl', 20),
					('Ciénega de Zimatl�n', 20),
					('San Bartolom� Ayautla', 20),
					('San Antonino el Alto', 20),
					('Chiquihuitl�n de Benito Juárez', 20),
					('Santiago Textitl�n', 20),
					('San Juan Bautista Tlacoatzintepec', 20),
					('San Lorenzo Texmel�can', 20),
					('Santiago Nacaltepec', 20),
					('San Juan Chilateca', 20),
					('San Juan Atepec', 20),
					('Magdalena Ocotl�n', 20),
					('San Juan Chicomez�chil', 20),
					('San José del Progreso', 20),
					('San Miguel Amatl�n', 20),
					('San Juan Lachigalla', 20),
					('Villa Talea de Castro', 20),
					('San Juan Bautista Lo de Soto', 20),
					('San Juan Taba�', 20),
					('San José Estancia Grande', 20),
					('San Mateo Cajonos', 20),
					('San Lorenzo', 20),
					('San Juan Petlapa', 20),
					('San Juan Quiahije', 20),
					('Santiago Miltepec', 20),
					('San Gabriel Mixtepec', 20),
					('Santiago Tamazola', 20),
					('San Mateo Nej�pam', 20),
					('Mariscala de Juárez', 20),
					('San Juan Bautista Coixtlahuaca', 20),
					('San Miguel Tequixtepec', 20),
					('San Agustín Atenango', 20),
					('Villa de Tamazul�pam del Progreso', 20),
					('San Andrés Lagunas', 20),
					('San Vicente Nu��', 20),
					('Santa María Chacho�pam', 20),
					('San Francisco Chind�a', 20),
					('San Mart�n Peras', 20),
					('Santa María del Rosario', 20),
					('San Mart�n Itunyoso', 20),
					('Santa María Tataltepec', 20),
					('San Francisco Nuxa�o', 20),
					('Yutanduchi de Guerrero', 20),
					('Santa María Xadani', 20),
					('Reforma de Pineda', 20),
					('Totontepec Villa de Morelos', 20),
					('San Miguel Quetzaltepec', 20),
					('Santa María Chimalapa', 20),
					('San Francisco Lachigol�', 20),
					('Santa Cruz Papalutla', 20),
					('San Pedro Totol�pam', 20),
					('San Juan Lajarcia', 20),
					('Salina Cruz', 20),
					('Magdalena Tequisistl�n', 20),
					('San Blas Atempa', 20),
					('Sitio de Xitlapehua', 20),
					('San Cristóbal Amatl�n', 20),
					('Santo Tom�s Tamazulapan', 20),
					('Santiago Xanica', 20),
					('San Francisco Telixtlahuaca', 20),
					('Santa María Colotepec', 20),
					('Nazareno Etla', 20),
					('San Miguel del Puerto', 20),
					('San Lorenzo Cacaotepec', 20),
					('Chalcatongo de Hidalgo', 20),
					('Santa María del Tule', 20),
					('San Pablo Tijaltepec', 20),
					('San Pedro Ixcatl�n', 20),
					('San Bernardo Mixtepec', 20),
					('Santa María Chilchotla', 20),
					('San Pedro Ixtlahuaca', 20),
					('Teotitl�n de Flores Mag�n', 20),
					('Santa María Coyotepec', 20),
					('San Antonio Nanahuat�pam', 20),
					('San Pablo Cuatro Venados', 20),
					('San Juan Bautista Cuicatl�n', 20),
					('Santa Cruz Zenzontepec', 20),
					('San Francisco Chapulapa', 20),
					('Villa Sola de Vega', 20),
					('San Pedro Jocotipac', 20),
					('Heroica Ciudad de Ejutla de Crespo', 20),
					('Abejones', 20),
					('Asunción Ocotl�n', 20),
					('San Juan Evangelista Analco', 20),
					('Santa Luc�a Ocotl�n', 20),
					('Santa Catarina Ixtepeji', 20),
					('La Pe', 20),
					('San Juan Yae�', 20),
					('San Vicente Coatl�n', 20),
					('Santo Domingo Roayaga', 20),
					('Santiago Llano Grande', 20),
					('Santiago Zoochila', 20),
					('Santiago Ixtayutla', 20),
					('Santiago Jocotepec', 20),
					('Santa María Huazolotitl�n', 20),
					('San Pedro y San Pablo Tequixtepec', 20),
					('San Juan Lachao', 20),
					('Asunción Cuyotepeji', 20),
					('Guadalupe de Ram�rez', 20),
					('San José Ayuquila', 20),
					('Santos Reyes Yucun�', 20),
					('San Francisco Teopan', 20),
					('Silacayo�pam', 20),
					('Santiago del Río', 20),
					('Santo Domingo Tonaltepec', 20),
					('San Sebasti�n Nicananduta', 20),
					('San Miguel Chicahua', 20),
					('San Juan Yucuita', 20),
					('San Sebasti�n Tecomaxtlahuaca', 20),
					('San Mart�n Huamel�lpam', 20),
					('Aquixtla', 21),
					('Libres', 21),
					('Xiutetelco', 21),
					('Chiautzingo', 21),
					('San Gregorio Atzompa', 21),
					('Atzitzihuac�n', 21),
					('Atzala', 21),
					('Chigmecatitl�n', 21),
					('Xicotl�n', 21),
					('Axutla', 21),
					('Coyotepec', 21),
					('Chila', 21),
					('Chilchotla', 21),
					('Acatzingo', 21),
					('Mixtla', 21),
					('Cuapiaxtla de Madero', 21),
					('Cañada Morelos', 21),
					('Yehualtepec', 21),
					('Atexcal', 21),
					('Zoquitl�n', 21),
					('Puebla', 21),
					('Ocoyucan', 21),
					('Xicotepec', 21),
					('Zihuateutla', 21),
					('San Felipe Tepatl�n', 21),
					('Hueytlalpan', 21),
					('Tuzamapan de Galeana', 21),
					('Acateno', 21),
					('Ixtacamaxtitl�n', 21),
					('Teteles de Avila Castillo', 21),
					('San Matías Tlalancaleca', 21),
					('Atlixco', 21),
					('San Diego la Mesa Tochimiltzingo', 21),
					('Tepexco', 21),
					('Ahuatl�n', 21),
					('Huehuetl�n el Chico', 21),
					('Tehuitzingo', 21),
					('Piaxtla', 21),
					('San Pedro Yeloixtlahuaca', 21),
					('Guadalupe Victoria', 21),
					('Nopalucan', 21),
					('Tepeaca', 21),
					('San Juan Atzompa', 21),
					('Chalchicomula de Sesma', 21),
					('Huitziltepec', 21),
					('Chapulco', 21),
					('Vicente Guerrero', 21),
					('Coxcatl�n', 21),
					('Cuautlancingo', 21),
					('Jalpan', 21),
					('Ahuazotepec', 21),
					('Chiconcuautla', 21),
					('Olintla', 21),
					('Ixtepec', 21),
					('Cuetzalan del Progreso', 21),
					('Xochiapulco', 21),
					('Tlatlauquitepec', 21),
					('Tepeyahualco', 21),
					('Domingo Arenas', 21),
					('Tianguismanalco', 21),
					('Cohuecan', 21),
					('San Mart�n Totoltepec', 21),
					('Tepexi de Rodr�guez', 21),
					('Ixcamilpa de Guerrero', 21),
					('Ahuehuetitla', 21),
					('Totoltepec de Guerrero', 21),
					('San José Chiapa', 21),
					('Chichiquila', 21),
					('General Felipe Ángeles', 21),
					('Tzicatlacoyan', 21),
					('Quecholac', 21),
					('Tochtepec', 21),
					('Juan N. Méndez', 21),
					('Zapotitl�n', 21),
					('Altepexi', 21),
					('San Miguel Xoxtla', 21),
					('Francisco Z. Mena', 21),
					('Honey', 21),
					('Tlapacoya', 21),
					('Tepango de Rodr�guez', 21),
					('Huitzilan de Serd�n', 21),
					('Jonotla', 21),
					('Ocotepec', 21),
					('Chignautla', 21),
					('San Felipe Teotlalcingo', 21),
					('San Jerónimo Tecuanipan', 21),
					('Iz�car de Matamoros', 21),
					('Chietla', 21),
					('Santa Catarina Tlaltempan', 21),
					('Cohetzala', 21),
					('Santa In�s Ahuatempan', 21),
					('Ixcaquixtla', 21),
					('San Miguel Ixitl�n', 21),
					('Lafragua', 21),
					('Soltepec', 21),
					('Tecali de Herrera', 21),
					('Los Reyes de Juárez', 21),
					('Esperanza', 21),
					('Xochitl�n Todos Santos', 21),
					('Nicolás Bravo', 21),
					('Eloxochitl�n', 21),
					('San Andrés Cholula', 21),
					('Tlacuilotepec', 21),
					('Tlaola', 21),
					('Tepetzintla', 21),
					('Camocuautla', 21),
					('Tenampulco', 21),
					('Hueytamalco', 21),
					('Zaragoza', 21),
					('Hueyapan', 21),
					('Tlahuapan', 21),
					('San Nicolás de los Ranchos', 21),
					('Huaquechula', 21),
					('Tlapanal�', 21),
					('Epatl�n', 21),
					('Jolalpan', 21),
					('Tulcingo', 21),
					('Tecomatl�n', 21),
					('San Jerónimo Xayacatl�n', 21),
					('San Nicolás Buenos Aires', 21),
					('Acajete', 21),
					('San Juan Atenco', 21),
					('La Magdalena Tlatlauquitepec', 21),
					('Palmar de Bravo', 21),
					('Tepeyahualco de Cuauhtémoc', 21),
					('Tepanco de López', 21),
					('Caltepec', 21),
					('San José Miahuatl�n', 21),
					('Coronango', 21),
					('Venustiano Carranza', 21),
					('Huauchinango', 21),
					('Zacatl�n', 21),
					('Hermenegildo Galeana', 21),
					('Huehuetla', 21),
					('Nauzontla', 21),
					('Tetela de Ocampo', 21),
					('Teziutl�n', 21),
					('Cuyoaco', 21),
					('Huejotzingo', 21),
					('Tochimilco', 21),
					('Acteopan', 21),
					('Teopantl�n', 21),
					('Zacapala', 21),
					('Chila de la Sal', 21),
					('Chinantla', 21),
					('Xayacatl�n de Bravo', 21),
					('Rafael Lara Grajales', 21),
					('Quimixtl�n', 21),
					('San Salvador el Seco', 21),
					('Santo Tom�s Hueyotlipan', 21),
					('San Salvador Huixcolotla', 21),
					('Tlanepantla', 21),
					('Tlacotepec de Benito Juárez', 21),
					('San Antonio Cañada', 21),
					('San Sebasti�n Tlacotepec', 21),
					('Tlaltenango', 21),
					('Amozoc', 21),
					('Pahuatl�n', 21),
					('Jopala', 21),
					('Amixtl�n', 21),
					('Zapotitl�n de Méndez', 21),
					('Caxhuacan', 21),
					('Cuautempan', 21),
					('Zautla', 21),
					('Atempan', 21),
					('San Salvador el Verde', 21),
					('Nealtican', 21),
					('Tepeojuma', 21),
					('Tilapa', 21),
					('Coatzingo', 21),
					('Chiautla', 21),
					('Cuayuca de Andrade', 21),
					('Guadalupe', 21),
					('Petlalcingo', 21),
					('Tlachichuca', 21),
					('Mazapiltepec de Juárez', 21),
					('Cuautinch�n', 21),
					('Huatlatlauca', 21),
					('Atzitzintla', 21),
					('Molcaxac', 21),
					('Santiago Miahuatl�n', 21),
					('Ajalpan', 21),
					('Coyomeapan', 21),
					('San Pedro Cholula', 21),
					('Tlaxco', 21),
					('Juan Galindo', 21),
					('Ahuacatl�n', 21),
					('Coatepec', 21),
					('Atlequizayan', 21),
					('Ayotoxco de Guerrero', 21),
					('Zacapoaxtla', 21),
					('Yaon�huac', 21),
					('San Mart�n Texmelucan', 21),
					('Calpan', 21),
					('Santa Isabel Cholula', 21),
					('Tepemaxalco', 21),
					('Xochiltepec', 21),
					('Teotlalco', 21),
					('Albino Zertuche', 21),
					('San Pablo Anicano', 21),
					('Acatl�n', 21),
					('Oriental', 21),
					('Tepatlaxco de Hidalgo', 21),
					('Aljojuca', 21),
					('Huehuetl�n el Grande', 21),
					('Tecamachalco', 21),
					('Atoyatempan', 21),
					('Tehuac�n', 21),
					('San Gabriel Chilac', 21),
					('Zinacatepec', 21),
					('Juan C. Bonilla', 21),
					('Pantepec', 21),
					('Naupan', 21),
					('Chignahuapan', 21),
					('Zongozotla', 21),
					('Xochitl�n de Vicente Suárez', 21),
					('Zoquiapan', 21),
					('El Marqu�s', 22),
					('San Joaqu�n', 22),
					('Huimilpan', 22),
					('Arroyo Seco', 22),
					('San Juan del Río', 22),
					('Pinal de Amoles', 22),
					('Ezequiel Montes', 22),
					('Quer�taro', 22),
					('Cadereyta de Montes', 22),
					('Corregidora', 22),
					('Landa de Matamoros', 22),
					('Tequisquiapan', 22),
					('Col�n', 22),
					('ToLimón', 22),
					('Pe�amiller', 22),
					('Amealco de Bonfil', 22),
					('Jalpan de Serra', 22),
					('Pedro Escobedo', 22),
					('Tulum', 23),
					('Benito Juárez', 23),
					('Felipe Carrillo Puerto', 23),
					('Bacalar', 23),
					('Solidaridad', 23),
					('Isla Mujeres', 23),
					('Othón P. Blanco', 23),
					('José María Morelos', 23),
					('Cozumel', 23),
					('Lázaro Cárdenas', 23),
					('Villa de Arriaga', 24),
					('Matehuala', 24),
					('Armadillo de los Infante', 24),
					('Cerritos', 24),
					('Ciudad Fern�ndez', 24),
					('Tanlaj�s', 24),
					('Axtla de Terrazas', 24),
					('Cerro de San Pedro', 24),
					('Salinas', 24),
					('Venado', 24),
					('Ciudad del Ma�z', 24),
					('Santa María del Río', 24),
					('Lagunillas', 24),
					('Coxcatl�n', 24),
					('Cedral', 24),
					('Villa de Guadalupe', 24),
					('Ebano', 24),
					('San Nicolás Tolentino', 24),
					('Tamasopo', 24),
					('San Antonio', 24),
					('San Mart�n Chalchicuautla', 24),
					('Mexquitic de Carmona', 24),
					('Villa de Ramos', 24),
					('Villa Hidalgo', 24),
					('Cárdenas', 24),
					('Rioverde', 24),
					('Tancanhuitz', 24),
					('Xilitla', 24),
					('Soledad de Graciano Sánchez', 24),
					('Charcas', 24),
					('Moctezuma', 24),
					('El Naranjo', 24),
					('Zaragoza', 24),
					('Aquism�n', 24),
					('Tampamol�n Corona', 24),
					('Matlapa', 24),
					('Vanegas', 24),
					('Villa de la Paz', 24),
					('Ciudad Valles', 24),
					('Villa Juárez', 24),
					('San Ciro de Acosta', 24),
					('San Vicente Tancuayalab', 24),
					('Tampac�n', 24),
					('Ahualulco', 24),
					('Santo Domingo', 24),
					('Villa de Arista', 24),
					('Alaquines', 24),
					('Tierra Nueva', 24),
					('Santa Catarina', 24),
					('Huehuetl�n', 24),
					('San Luis Potos�', 24),
					('Catorce', 24),
					('Guadalc�zar', 24),
					('Tamu�n', 24),
					('Villa de Reyes', 24),
					('Ray�n', 24),
					('Tanqui�n de Escobedo', 24),
					('Tamazunchale', 24),
					('Cosal�', 25),
					('Sinaloa', 25),
					('Culiac�n', 25),
					('Angostura', 25),
					('Rosario', 25),
					('Guasave', 25),
					('Escuinapa', 25),
					('Badiraguato', 25),
					('El Fuerte', 25),
					('Salvador Alvarado', 25),
					('Elota', 25),
					('Mocorito', 25),
					('Mazatl�n', 25),
					('Navolato', 25),
					('Choix', 25),
					('San Ignacio', 25),
					('Ahome', 25),
					('Concordia', 25),
					('Santa Cruz', 26),
					('Huachinera', 26),
					('Santa Ana', 26),
					('Villa Pesqueira', 26),
					('Ray�n', 26),
					('Guaymas', 26),
					('Bacanora', 26),
					('San Miguel de Horcasitas', 26),
					('Atil', 26),
					('Nacozari de Garc�a', 26),
					('Hu�sabas', 26),
					('San Pedro de la Cueva', 26),
					('Aconchi', 26),
					('Etchojoa', 26),
					('Sahuaripa', 26),
					('Alamos', 26),
					('Caborca', 26),
					('Pitiquito', 26),
					('Naco', 26),
					('Granados', 26),
					('Arizpe', 26),
					('Hu�pac', 26),
					('Navojoa', 26),
					('La Colorada', 26),
					('Rosario', 26),
					('San Luis Río Colorado', 26),
					('S�ric', 26),
					('Imuris', 26),
					('Bacerac', 26),
					('Villa Hidalgo', 26),
					('Tepache', 26),
					('San Felipe de Jesús', 26),
					('Empalme', 26),
					('Soyopa', 26),
					('Hermosillo', 26),
					('Tubutama', 26),
					('Fronteras', 26),
					('Cumpas', 26),
					('Bacoachi', 26),
					('Ures', 26),
					('B�cum', 26),
					('Suaqui Grande', 26),
					('Onavas', 26),
					('General Plutarco Elías Calles', 26),
					('Trincheras', 26),
					('Magdalena', 26),
					('N�cori Chico', 26),
					('Cananea', 26),
					('Opodepe', 26),
					('Cajeme', 26),
					('San Ignacio Río Muerto', 26),
					('Arivechi', 26),
					('Carb�', 26),
					('Oquitoa', 26),
					('Bavispe', 26),
					('Moctezuma', 26),
					('Divisaderos', 26),
					('Bavi�cora', 26),
					('Benito Juárez', 26),
					('San Javier', 26),
					('Y�cora', 26),
					('Altar', 26),
					('Nogales', 26),
					('Agua Prieta', 26),
					('Bacad�huachi', 26),
					('Cucurpe', 26),
					('Ban�michi', 26),
					('Huatabampo', 26),
					('Mazat�n', 26),
					('Quiriego', 26),
					('Puerto Pe�asco', 26),
					('Benjam�n Hill', 26),
					('Jalpa de Méndez', 27),
					('Centla', 27),
					('Paraíso', 27),
					('Tenosique', 27),
					('Comalcalco', 27),
					('Teapa', 27),
					('Centro', 27),
					('Macuspana', 27),
					('Emiliano Zapata', 27),
					('Cárdenas', 27),
					('Tacotalpa', 27),
					('Nacajuca', 27),
					('Jonuta', 27),
					('Cunduac�n', 27),
					('Balanc�n', 27),
					('Huimanguillo', 27),
					('Jalapa', 27),
					('Victoria', 28),
					('San Nicolás', 28),
					('Villagr�n', 28),
					('Miguel Alemán', 28),
					('Burgos', 28),
					('El Mante', 28),
					('Valle Hermoso', 28),
					('Padilla', 28),
					('Palmillas', 28),
					('Reynosa', 28),
					('González', 28),
					('G��mez', 28),
					('Jiménez', 28),
					('Jaumave', 28),
					('Mier', 28),
					('Ciudad Madero', 28),
					('Nuevo Morelos', 28),
					('Cruillas', 28),
					('Mainero', 28),
					('Nuevo Laredo', 28),
					('Méndez', 28),
					('Gómez Far�as', 28),
					('Matamoros', 28),
					('Abasolo', 28),
					('Bustamante', 28),
					('Camargo', 28),
					('Aldama', 28),
					('Llera', 28),
					('Soto la Marina', 28),
					('Tula', 28),
					('Guerrero', 28),
					('Tampico', 28),
					('Antiguo Morelos', 28),
					('San Fernando', 28),
					('Hidalgo', 28),
					('Ocampo', 28),
					('Río Bravo', 28),
					('Xicot�ncatl', 28),
					('Casas', 28),
					('San Carlos', 28),
					('Miquihuana', 28),
					('Gustavo D�az Ordaz', 28),
					('Altamira', 28),
					('Tepeyanco', 29),
					('Nanacamilpa de Mariano Arista', 29),
					('Yauhquemehcan', 29),
					('Emiliano Zapata', 29),
					('Santa Cruz Tlaxcala', 29),
					('San Jerónimo Zacualpan', 29),
					('San Francisco Tetlanohcan', 29),
					('Santa Ana Nopalucan', 29),
					('Benito Juárez', 29),
					('Tetla de la Solidaridad', 29),
					('Huamantla', 29),
					('Ziltlalt�pec de Trinidad Sánchez Santos', 29),
					('Santa Apolonia Teacalco', 29),
					('Papalotla de Xicoht�ncatl', 29),
					('Tenancingo', 29),
					('San Juan Huactzinco', 29),
					('Apizaco', 29),
					('Tocatl�n', 29),
					('Cuapiaxtla', 29),
					('Contla de Juan Cuamatzi', 29),
					('San Lorenzo Axocomanitla', 29),
					('Acuamanala de Miguel Hidalgo', 29),
					('Totolac', 29),
					('Tlaxco', 29),
					('San Lucas Tecopilco', 29),
					('Lázaro Cárdenas', 29),
					('Amaxac de Guerrero', 29),
					('San Dami�n Tex�loc', 29),
					('La Magdalena Tlaltelulco', 29),
					('Ixtacuixtla de Mariano Matamoros', 29),
					('Sanct�rum de Lázaro Cárdenas', 29),
					('Muñoz de Domingo Arenas', 29),
					('San José Teacalco', 29),
					('Ixtenco', 29),
					('Nat�vitas', 29),
					('Xicohtzinco', 29),
					('Mazatecochco de José María Morelos', 29),
					('Santa Isabel Xiloxoxtla', 29),
					('Espa�ita', 29),
					('Xaloztoc', 29),
					('Atltzayanca', 29),
					('Cuaxomulco', 29),
					('Zacatelco', 29),
					('Teolocholco', 29),
					('Panotla', 29),
					('Hueyotlipan', 29),
					('Xaltocan', 29),
					('Terrenate', 29),
					('Apetatitl�n de Antonio Carvajal', 29),
					('Tetlatlahuca', 29),
					('Chiautempan', 29),
					('San Pablo del Monte', 29),
					('Tlaxcala', 29),
					('Calpulalpan', 29),
					('Atlangatepec', 29),
					('Tzompantepec', 29),
					('El Carmen Tequexquitla', 29),
					('Tepetitla de Lardiz�bal', 29),
					('Santa Catarina Ayometla', 29),
					('Santa Cruz Quilehtla', 29),
					('Tlalnelhuayocan', 30),
					('Las Vigas de Ram�rez', 30),
					('Acatl�n', 30),
					('Emiliano Zapata', 30),
					('Pueblo Viejo', 30),
					('Chontla', 30),
					('Cerro Azul', 30),
					('Zacualpan', 30),
					('Castillo de Teayo', 30),
					('Coyutla', 30),
					('San Rafael', 30),
					('Nautla', 30),
					('Tlaltetela', 30),
					('Coscomatepec', 30),
					('Camar�n de Tejeda', 30),
					('Mariano Escobedo', 30),
					('Río Blanco', 30),
					('Xoxocotla', 30),
					('Omealca', 30),
					('Cotaxtla', 30),
					('Tlalixcoyan', 30),
					('Acula', 30),
					('José Azueta', 30),
					('Hueyapan de Ocampo', 30),
					('San Juan Evangelista', 30),
					('Cosoleacaque', 30),
					('Jesús Carranza', 30),
					('Banderilla', 30),
					('Jilotepec', 30),
					('Coatepec', 30),
					('La Antigua', 30),
					('Plat�n Sánchez', 30),
					('Chinampa de Gorostiza', 30),
					('Ilamatl�n', 30),
					('�lamo Temapache', 30),
					('Mecatl�n', 30),
					('Gutiérrez Zamora', 30),
					('Las Minas', 30),
					('Colipa', 30),
					('Huatusco', 30),
					('Tepatlaxco', 30),
					('Boca del Río', 30),
					('C�rdoba', 30),
					('Huiloapan de Cuauhtémoc', 30),
					('Magdalena', 30),
					('Atoyac', 30),
					('Texhuac�n', 30),
					('Carlos A. Carrillo', 30),
					('Tlacojalpan', 30),
					('San Andrés Tuxtla', 30),
					('Pajapan', 30),
					('J�ltipan', 30),
					('Agua Dulce', 30),
					('Ixhuac�n de los Reyes', 30),
					('Tlacolulan', 30),
					('Juchique de Ferrer', 30),
					('Puente Nacional', 30),
					('Tempoal', 30),
					('Ixcatepec', 30),
					('Tancoco', 30),
					('Tlachichilco', 30),
					('Zozocolco de Hidalgo', 30),
					('Espinal', 30),
					('Jalacingo', 30),
					('Landero y Coss', 30),
					('Totutla', 30),
					('Chocam�n', 30),
					('Manlio Fabio Altamirano', 30),
					('Atzacan', 30),
					('Aquila', 30),
					('Tequila', 30),
					('Cuichapa', 30),
					('Tehuipango', 30),
					('Alvarado', 30),
					('Tlacotalpan', 30),
					('Santiago Sochiapan', 30),
					('Soteapan', 30),
					('Oluta', 30),
					('Ixhuatl�n del Sureste', 30),
					('Uxpanapa', 30),
					('Xalapa', 30),
					('Acajete', 30),
					('Miahuatl�n', 30),
					('Cosautl�n de Carvajal', 30),
					('P�nuco', 30),
					('Chalma', 30),
					('Tamal�n', 30),
					('Texcatepec', 30),
					('Tihuatl�n', 30),
					('Coahuitl�n', 30),
					('Martínez de la Torre', 30),
					('Tenochtitl�n', 30),
					('Jalcomulco', 30),
					('Alpatl�huac', 30),
					('Zentla', 30),
					('Rafael Delgado', 30),
					('Nogales', 30),
					('Astacinga', 30),
					('Coetzala', 30),
					('Carrillo Puerto', 30),
					('Tierra Blanca', 30),
					('Ixmatlahuacan', 30),
					('Chacaltianguis', 30),
					('Angel R. Cabada', 30),
					('Acayucan', 30),
					('Oteapan', 30),
					('Hidalgotitl�n', 30),
					('Perote', 30),
					('Coacoatzintla', 30),
					('Actopan', 30),
					('Paso de Ovejas', 30),
					('Tantoyuca', 30),
					('El Higo', 30),
					('Huayacocotla', 30),
					('Chicontepec', 30),
					('Coxquihui', 30),
					('Papantla', 30),
					('Altotonga', 30),
					('Yecuatla', 30),
					('Tlacotepec de Mej�a', 30),
					('Ixhuatl�n del Caf�', 30),
					('Medell�n', 30),
					('Fort�n', 30),
					('Soledad Atzompa', 30),
					('Tlilapan', 30),
					('Amatl�n de los Reyes', 30),
					('Los Reyes', 30),
					('Tres Valles', 30),
					('Otatitl�n', 30),
					('Juan Rodr�guez Clara', 30),
					('Tatahuicapan de Juárez', 30),
					('Texistepec', 30),
					('Coatzacoalcos', 30),
					('Xico', 30),
					('Villa Aldama', 30),
					('Tepetl�n', 30),
					('Apazapan', 30),
					('Tampico Alto', 30),
					('Citlalt�petl', 30),
					('Tepetzintla', 30),
					('Benito Juárez', 30),
					('Cazones de Herrera', 30),
					('Coatzintla', 30),
					('Tlapacoyan', 30),
					('Misantla', 30),
					('Tenampa', 30),
					('La Perla', 30),
					('Soledad de Doblado', 30),
					('Ixhuatlancillo', 30),
					('Camerino Z. Mendoza', 30),
					('Atlahuilco', 30),
					('Cuitl�huac', 30),
					('Zongolica', 30),
					('Ignacio de la Llave', 30),
					('Amatitl�n', 30),
					('Playa Vicente', 30),
					('Catemaco', 30),
					('Sayula de Alemán', 30),
					('Nanchital de Lázaro Cárdenas del Río', 30),
					('Las Choapas', 30),
					('Rafael Lucio', 30),
					('Naolinco', 30),
					('Teocelo', 30),
					('Veracruz', 30),
					('Chiconamel', 30),
					('Tantima', 30),
					('Zontecomatl�n de López y Fuentes', 30),
					('Tuxpan', 30),
					('Filomeno Mata', 30),
					('Tecolutla', 30),
					('Tatatila', 30),
					('Vega de Alatorre', 30),
					('Calcahualco', 30),
					('Comapa', 30),
					('Orizaba', 30),
					('Maltrata', 30),
					('Tlaquilpa', 30),
					('Naranjal', 30),
					('Paso del Macho', 30),
					('Tezonapa', 30),
					('Cosamaloapan de Carpio', 30),
					('Tuxtilla', 30),
					('Santiago Tuxtla', 30),
					('Chinameca', 30),
					('Zaragoza', 30),
					('Minatitl�n', 30),
					('Ayahualulco', 30),
					('Tonay�n', 30),
					('Alto Lucero de Gutiérrez Barrios', 30),
					('Ursulo Galván', 30),
					('Ozuluama de Mascare�as', 30),
					('Naranjos Amatl�n', 30),
					('Tamiahua', 30),
					('Ixhuatl�n de Madero', 30),
					('Chumatl�n', 30),
					('Poza Rica de Hidalgo', 30),
					('Atzalan', 30),
					('Chiconquiaco', 30),
					('Sochiapa', 30),
					('Tomatl�n', 30),
					('Jamapa', 30),
					('Ixtaczoquitl�n', 30),
					('Acultzingo', 30),
					('San Andrés Tenejapan', 30),
					('Yanga', 30),
					('Mixtla de Altamirano', 30),
					('Lerdo de Tejada', 30),
					('Saltabarranca', 30),
					('Isla', 30),
					('Mecayapan', 30),
					('Soconusco', 30),
					('Moloac�n', 30),
					('Yoba�n', 31),
					('Hoct�n', 31),
					('Tekal de Venegas', 31),
					('Huh�', 31),
					('Dzoncauich', 31),
					('Tizim�n', 31),
					('Tixcacalcupul', 31),
					('Samahil', 31),
					('Sacalum', 31),
					('Chumayel', 31),
					('Tixmehuac', 31),
					('Yaxkukul', 31),
					('Acanceh', 31),
					('Cacalch�n', 31),
					('Teya', 31),
					('Cuzam�', 31),
					('Buctzotz', 31),
					('Sudzal', 31),
					('Tinum', 31),
					('Valladolid', 31),
					('Abal�', 31),
					('Oxkutzcab', 31),
					('Peto', 31),
					('Chicxulub Pueblo', 31),
					('Celest�n', 31),
					('Telchac Puerto', 31),
					('Baca', 31),
					('Dzidzant�n', 31),
					('Hocab�', 31),
					('Dzilam de Bravo', 31),
					('Quintana Roo', 31),
					('Espita', 31),
					('Cuncunul', 31),
					('Chochol�', 31),
					('Dz�n', 31),
					('Teabo', 31),
					('Tzucacab', 31),
					('Uc�', 31),
					('Um�n', 31),
					('Tixkokob', 31),
					('Tepak�n', 31),
					('Sanahcat', 31),
					('Cenotillo', 31),
					('Sotuta', 31),
					('Chichimil�', 31),
					('Maxcan�', 31),
					('Muna', 31),
					('Mama', 31),
					('Tahdzi�', 31),
					('Conkal', 31),
					('Timucuy', 31),
					('Sinanch�', 31),
					('Muxupip', 31),
					('Tekant�', 31),
					('Sey�', 31),
					('San Felipe', 31),
					('Kantunil', 31),
					('Calotmul', 31),
					('Chemax', 31),
					('Tecoh', 31),
					('Ticul', 31),
					('Yaxcab�', 31),
					('Akil', 31),
					('Progreso', 31),
					('Tetiz', 31),
					('Dzemul', 31),
					('Motul', 31),
					('Tahmek', 31),
					('Izamal', 31),
					('Dzilam González', 31),
					('Tunk�s', 31),
					('Río Lagartos', 31),
					('Kaua', 31),
					('Opich�n', 31),
					('Man�', 31),
					('Mayap�n', 31),
					('Chacsink�n', 31),
					('Hunucm�', 31),
					('Tixp�hual', 31),
					('Bokob�', 31),
					('Suma', 31),
					('Hom�n', 31),
					('Sucil�', 31),
					('Tekit', 31),
					('Chankom', 31),
					('Uayma', 31),
					('Halach�', 31),
					('Santa Elena', 31),
					('Chikindzonot', 31),
					('Ixil', 31),
					('Kanas�n', 31),
					('Cansahcab', 31),
					('Mococh�', 31),
					('Temax', 31),
					('Xocchel', 31),
					('Panab�', 31),
					('Dzit�s', 31),
					('Temoz�n', 31),
					('Tekom', 31),
					('Kopom�', 31),
					('Chapab', 31),
					('Cantamayec', 31),
					('Tekax', 31),
					('M�rida', 31),
					('Kinchil', 31),
					('Telchac Pueblo', 31),
					('Concepción del Oro', 32),
					('Villa de Cos', 32),
					('Cuauhtémoc', 32),
					('Pinos', 32),
					('Jerez', 32),
					('Huanusco', 32),
					('Trinidad Garc�a de la Cadena', 32),
					('Zacatecas', 32),
					('Miguel Auza', 32),
					('Guadalupe', 32),
					('Villa González Ortega', 32),
					('ValParaíso', 32),
					('El Plateado de Joaqu�n Amaro', 32),
					('Benito Juárez', 32),
					('Juchipila', 32),
					('Mazapil', 32),
					('Calera', 32),
					('General P�nfilo Natera', 32),
					('Fresnillo', 32),
					('Susticac�n', 32),
					('Momax', 32),
					('Nochistlán de Mejía', 32),
					('Vetagrande', 32),
					('Río Grande', 32),
					('Genaro Codina', 32),
					('Villa García', 32),
					('Jiménez del Teul', 32),
					('Tabasco', 32),
					('Santa María de la Paz', 32),
					('Juan Aldama', 32),
					('General Enrique Estrada', 32),
					('Loreto', 32),
					('Sain Alto', 32),
					('Tepetongo', 32),
					('Tepechitlán', 32),
					('Apozol', 32),
					('Melchor Ocampo', 32),
					('Ca�itas de Felipe Pescador', 32),
					('Ojocaliente', 32),
					('Villa Hidalgo', 32),
					('Monte Escobedo', 32),
					('Tlaltenango de Sánchez Román', 32),
					('Mezquital del Oro', 32),
					('Morelos', 32),
					('General Francisco R. Murgu�a', 32),
					('Trancoso', 32),
					('Noria de Ángeles', 32),
					('Chalchihuites', 32),
					('Jalpa', 32),
					('Te�l de González Ortega', 32),
					('Moyahua de Estrada', 32),
					('El Salvador', 32),
					('Pánuco', 32),
					('Luis Moya', 32),
					('Sombrerete', 32),
					('Villanueva', 32),
					('Atolinga', 32),
					('Apulco', 32)");
    }
}
